from __future__ import annotations

import argparse
import json
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

from pretrip_candidate_generation import generate_pretrip_candidates_from_gpx
from pretrip_geojson_import import import_pretrip_geojson_candidates
from pretrip_gis_perception import build_gpx_gis_perception
from pretrip_gpx_corpus import (
    build_checkpoint_event_candidates,
    build_reference_track_display_geometry,
    build_reference_track_summary,
    build_segment_display_geometry,
    write_json,
)
from pretrip_models import PreTripArtifactKind, PreTripPackage
from pretrip_source_ingest import ingest_source_artifact, sha256_file, summarize_gpx
from runtime_debug_models import RuntimeDebugEvent


IMPORTER_VERSION = "0.1.0"
ImportProfile = Literal["mac-workstation", "pi-offline", "pi-online-explicit"]
ImportStage = Literal["pretrip", "post_analysis"]
OFFLINE_PROFILES = {"mac-workstation", "pi-offline"}


@dataclass(frozen=True)
class PretripImportRequest:
    project_id: str
    # Backward-compatible name for the selected golden route GPX. In pretrip,
    # this is not the user's already-walked track.
    primary_gpx: Path
    workspace_root: Path
    reference_dir: Path | None = None
    reference_gpx_paths: tuple[Path, ...] = ()
    profile: ImportProfile = "pi-offline"
    template_project_root: Path | None = None
    checkpoint_spacing_m: float = 1_500.0
    max_reference_display_points: int = 1_000
    overwrite: bool = False
    import_timestamp: str | None = None
    import_stage: ImportStage = "pretrip"


def run_pretrip_import(request: PretripImportRequest) -> dict[str, Any]:
    _validate_request(request)
    project_root = request.workspace_root.expanduser() / request.project_id
    _prepare_project_root(
        project_root=project_root,
        template_project_root=request.template_project_root,
        overwrite=request.overwrite,
    )

    primary_gpx = request.primary_gpx.expanduser().resolve()
    reference_paths = _reference_paths(request, primary_gpx=primary_gpx)
    import_timestamp = request.import_timestamp or _utc_now()
    primary_artifact_id = f"artifact.gpx.{request.project_id}"
    package_id = f"pretrip.{request.project_id}.v0"

    route_summary = summarize_gpx(primary_gpx, primary_artifact_id)
    candidate_result = generate_pretrip_candidates_from_gpx(
        primary_gpx,
        checkpoint_spacing_m=request.checkpoint_spacing_m,
        source_ref=primary_artifact_id,
    )
    source_artifacts = [
        ingest_source_artifact(
            artifact_id=primary_artifact_id,
            path=primary_gpx,
            kind=PreTripArtifactKind.GPX,
            media_type="application/gpx+xml",
            method="pretrip_import.run_pretrip_import",
            metadata={
                "role": _golden_route_role(request),
                "imported_at": import_timestamp,
                "import_stage": request.import_stage,
                "actual_user_track_available": request.import_stage == "post_analysis",
                "pretrip_selected_reference_route": request.import_stage == "pretrip",
            },
        )
    ]
    for index, reference_path in enumerate(reference_paths, start=1):
        reference_id = f"{primary_artifact_id}.reference.{index:03d}"
        source_artifacts.append(
            ingest_source_artifact(
                artifact_id=reference_id,
                path=reference_path,
                kind=PreTripArtifactKind.GPX,
                media_type="application/gpx+xml",
                method="pretrip_import.run_pretrip_import",
                metadata={"role": "reference_track", "imported_at": import_timestamp},
            )
        )

    package = PreTripPackage(
        package_id=package_id,
        project_id=request.project_id,
        version=IMPORTER_VERSION,
        route_summary=route_summary,
        source_artifacts=source_artifacts,
        checkpoint_candidates=candidate_result.checkpoint_candidates,
        segment_candidates=candidate_result.segment_candidates,
        readiness_notes=[
            "Generated by standalone pretrip importer; planning candidate only.",
            (
                "Golden route（出發前選定的主參考路線）is not proof that the "
                "user has already walked this route."
            ),
            "Standalone importer（獨立匯入程式）output is not Phase 1 runtime safety truth.",
        ],
    )

    map_context = _build_map_context(
        project_id=request.project_id,
        checkpoint_candidates=candidate_result.checkpoint_candidates,
    )
    map_candidates = import_pretrip_geojson_candidates(
        map_context,
        uri="normalized/map/map_context.geojson",
        source_ref="normalized/map/map_context.geojson",
    )
    reference_tracks = build_reference_track_summary(
        project_id=request.project_id,
        primary_gpx_path=primary_gpx,
        reference_gpx_paths=reference_paths,
        primary_artifact_id=primary_artifact_id,
    )
    checkpoint_events = build_checkpoint_event_candidates(
        project_id=request.project_id,
        route_gpx_path=primary_gpx,
        checkpoint_candidates=candidate_result.checkpoint_candidates,
        route_artifact_id=primary_artifact_id,
    )
    segment_display_geometry = build_segment_display_geometry(
        project_id=request.project_id,
        route_gpx_path=primary_gpx,
        segment_candidates=candidate_result.segment_candidates,
        route_artifact_id=primary_artifact_id,
    )
    reference_display_geometry = build_reference_track_display_geometry(
        project_id=request.project_id,
        primary_gpx_path=primary_gpx,
        reference_gpx_paths=reference_paths,
        primary_artifact_id=primary_artifact_id,
        max_points_per_track=request.max_reference_display_points,
    )
    gis_perception_result = build_gpx_gis_perception(
        project_id=request.project_id,
        primary_gpx_path=primary_gpx,
        reference_gpx_paths=reference_paths,
        primary_artifact_id=primary_artifact_id,
    )

    output_refs = {
        "package_ref": "outputs/pretrip_package.json",
        "route_summary_ref": "normalized/routes/route_summary.json",
        "map_context_ref": "normalized/map/map_context.geojson",
        "map_candidates_ref": "candidates/map_candidates.json",
        "checkpoint_candidates_ref": "candidates/checkpoints.json",
        "segment_candidates_ref": "candidates/segments.json",
        "route_note_candidates_ref": "candidates/route_note_candidates.json",
        "gis_perception_ai_judgements_ref": "outputs/gis_perception_ai_judgements.json",
        "route_note_ln_proposals_ref": "outputs/route_note_ln_proposals.json",
        "gis_perception_candidates_ref": "outputs/gis_perception_candidates.json",
        "reference_tracks_ref": "outputs/reference_tracks.json",
        "reference_track_display_geometry_ref": "outputs/reference_track_display_geometry.json",
        "checkpoint_events_ref": "outputs/checkpoint_events.json",
        "segment_display_geometry_ref": "outputs/segment_display_geometry.json",
        "import_manifest_ref": "outputs/import_manifest.json",
        "admin_projection_ref": "outputs/admin_projection.json",
        "debug_projection_events_ref": "outputs/debug_projection_events.jsonl",
    }
    manifest = _build_import_manifest(
        request=request,
        project_root=project_root,
        primary_gpx=primary_gpx,
        reference_paths=reference_paths,
        import_timestamp=import_timestamp,
        output_refs=output_refs,
        route_summary=route_summary.model_dump(mode="json"),
        checkpoint_count=len(candidate_result.checkpoint_candidates),
        segment_count=len(candidate_result.segment_candidates),
        gis_perception=gis_perception_result.gis_perception.model_dump(mode="json"),
        gis_perception_ai_judgements=gis_perception_result.gis_perception_ai_judgements.model_dump(mode="json"),
        route_note_candidates=gis_perception_result.route_note_candidates.model_dump(mode="json"),
        route_note_ln_proposals=gis_perception_result.route_note_ln_proposals.model_dump(mode="json"),
    )
    admin_projection = _build_admin_projection(
        request=request,
        route_summary=route_summary.model_dump(mode="json"),
        output_refs=output_refs,
        reference_track_count=len(reference_paths),
        checkpoint_count=len(candidate_result.checkpoint_candidates),
        segment_count=len(candidate_result.segment_candidates),
        gis_perception=gis_perception_result.gis_perception.model_dump(mode="json"),
        gis_perception_ai_judgements=gis_perception_result.gis_perception_ai_judgements.model_dump(mode="json"),
    )
    debug_events = _build_debug_projection_events(
        request=request,
        import_timestamp=import_timestamp,
        route_summary=route_summary.model_dump(mode="json"),
        reference_track_count=len(reference_paths),
        checkpoint_count=len(candidate_result.checkpoint_candidates),
        segment_count=len(candidate_result.segment_candidates),
        gis_perception=gis_perception_result.gis_perception.model_dump(mode="json"),
        gis_perception_ai_judgements=gis_perception_result.gis_perception_ai_judgements.model_dump(mode="json"),
    )
    manifest["counts"]["debug_projection_event_count"] = len(debug_events)

    write_json(project_root / output_refs["package_ref"], package.model_dump(mode="json"))
    write_json(project_root / output_refs["route_summary_ref"], route_summary.model_dump(mode="json"))
    write_json(project_root / output_refs["map_context_ref"], map_context)
    write_json(project_root / output_refs["map_candidates_ref"], map_candidates.model_dump(mode="json"))
    write_json(
        project_root / output_refs["checkpoint_candidates_ref"],
        [candidate.model_dump(mode="json") for candidate in candidate_result.checkpoint_candidates],
    )
    write_json(
        project_root / output_refs["segment_candidates_ref"],
        [candidate.model_dump(mode="json") for candidate in candidate_result.segment_candidates],
    )
    write_json(
        project_root / output_refs["route_note_candidates_ref"],
        gis_perception_result.route_note_candidates.model_dump(mode="json"),
    )
    write_json(
        project_root / output_refs["gis_perception_ai_judgements_ref"],
        gis_perception_result.gis_perception_ai_judgements.model_dump(mode="json"),
    )
    write_json(
        project_root / output_refs["route_note_ln_proposals_ref"],
        gis_perception_result.route_note_ln_proposals.model_dump(mode="json"),
    )
    write_json(
        project_root / output_refs["gis_perception_candidates_ref"],
        gis_perception_result.gis_perception.model_dump(mode="json"),
    )
    write_json(project_root / output_refs["reference_tracks_ref"], reference_tracks)
    write_json(
        project_root / output_refs["reference_track_display_geometry_ref"],
        reference_display_geometry,
    )
    write_json(project_root / output_refs["checkpoint_events_ref"], checkpoint_events)
    write_json(project_root / output_refs["segment_display_geometry_ref"], segment_display_geometry)
    write_json(project_root / output_refs["import_manifest_ref"], manifest)
    write_json(project_root / output_refs["admin_projection_ref"], admin_projection)
    _write_jsonl(project_root / output_refs["debug_projection_events_ref"], debug_events)
    project_payload = _project_payload(
        project_root=project_root,
        project_id=request.project_id,
        output_refs=output_refs,
        route_summary=route_summary.model_dump(mode="json"),
        reference_track_count=len(reference_paths),
        checkpoint_count=len(candidate_result.checkpoint_candidates),
        segment_count=len(candidate_result.segment_candidates),
        gis_perception=gis_perception_result.gis_perception.model_dump(mode="json"),
        gis_perception_ai_judgements=gis_perception_result.gis_perception_ai_judgements.model_dump(mode="json"),
        import_stage=request.import_stage,
    )
    write_json(project_root / "project.json", project_payload)
    return manifest


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Import a local GPX corpus into a Scout pretrip project workspace."
    )
    parser.add_argument("--project-id", required=True)
    route_group = parser.add_mutually_exclusive_group(required=True)
    route_group.add_argument(
        "--golden-route-gpx",
        type=Path,
        help=(
            "Selected golden route GPX for pretrip planning; this is a similar "
            "reference route, not the user's actual track before departure."
        ),
    )
    route_group.add_argument(
        "--primary-gpx",
        type=Path,
        help="Deprecated alias for --golden-route-gpx.",
    )
    parser.add_argument("--reference-dir", type=Path)
    parser.add_argument("--reference-gpx", type=Path, action="append", default=[])
    parser.add_argument("--workspace-root", type=Path, required=True)
    parser.add_argument(
        "--profile",
        choices=("mac-workstation", "pi-offline", "pi-online-explicit"),
        default="pi-offline",
    )
    parser.add_argument("--template-project-root", type=Path)
    parser.add_argument("--checkpoint-spacing-m", type=float, default=1_500.0)
    parser.add_argument("--max-reference-display-points", type=int, default=1_000)
    parser.add_argument(
        "--import-stage",
        choices=("pretrip", "post_analysis"),
        default="pretrip",
    )
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args(argv)
    golden_route_gpx = args.golden_route_gpx or args.primary_gpx

    manifest = run_pretrip_import(
        PretripImportRequest(
            project_id=args.project_id,
            primary_gpx=golden_route_gpx,
            reference_dir=args.reference_dir,
            reference_gpx_paths=tuple(args.reference_gpx),
            workspace_root=args.workspace_root,
            profile=args.profile,
            template_project_root=args.template_project_root,
            checkpoint_spacing_m=args.checkpoint_spacing_m,
            max_reference_display_points=args.max_reference_display_points,
            overwrite=args.overwrite,
            import_stage=args.import_stage,
        )
    )
    print(json.dumps(manifest, indent=2, ensure_ascii=False, sort_keys=True))


def _validate_request(request: PretripImportRequest) -> None:
    if not request.project_id:
        raise ValueError("project_id is required")
    if request.profile not in {"mac-workstation", "pi-offline", "pi-online-explicit"}:
        raise ValueError(f"unsupported import profile: {request.profile}")
    if request.profile == "pi-online-explicit":
        raise ValueError("pi-online-explicit is reserved for a later audited network slice")
    if request.import_stage not in {"pretrip", "post_analysis"}:
        raise ValueError(f"unsupported import stage: {request.import_stage}")
    if request.checkpoint_spacing_m <= 0:
        raise ValueError("checkpoint_spacing_m must be greater than 0")
    if request.max_reference_display_points <= 0:
        raise ValueError("max_reference_display_points must be greater than 0")
    primary = request.primary_gpx.expanduser()
    if not primary.exists():
        raise FileNotFoundError(f"golden route GPX not found: {primary}")
    if request.reference_dir is not None and not request.reference_dir.expanduser().exists():
        raise FileNotFoundError(f"reference directory not found: {request.reference_dir}")
    if request.template_project_root is not None and not request.template_project_root.expanduser().exists():
        raise FileNotFoundError(f"template project root not found: {request.template_project_root}")


def _prepare_project_root(
    *,
    project_root: Path,
    template_project_root: Path | None,
    overwrite: bool,
) -> None:
    if project_root.exists():
        if not overwrite:
            raise FileExistsError(f"project workspace already exists: {project_root}")
        shutil.rmtree(project_root)
    if template_project_root is not None:
        shutil.copytree(template_project_root.expanduser(), project_root)
    else:
        project_root.mkdir(parents=True)


def _reference_paths(request: PretripImportRequest, *, primary_gpx: Path) -> list[Path]:
    candidates = [path.expanduser().resolve() for path in request.reference_gpx_paths]
    if request.reference_dir is not None:
        candidates.extend(sorted(path.resolve() for path in request.reference_dir.expanduser().glob("*.gpx")))
    unique: dict[str, Path] = {}
    for path in candidates:
        if path == primary_gpx:
            continue
        if not path.exists():
            raise FileNotFoundError(f"reference GPX not found: {path}")
        unique[path.as_posix()] = path
    return [unique[key] for key in sorted(unique)]


def _build_map_context(*, project_id: str, checkpoint_candidates: list[Any]) -> dict[str, Any]:
    coordinates = [
        [round(candidate.lon, 7), round(candidate.lat, 7)]
        for candidate in checkpoint_candidates
    ]
    if len(coordinates) < 2:
        raise ValueError("At least two checkpoint candidates are required for map context")

    return {
        "type": "FeatureCollection",
        "properties": {
            "source": "pretrip_standalone_importer",
            "source_version": IMPORTER_VERSION,
            "confidence": 0.66,
            "known_staleness_risk": "medium",
            "notes": (
                "Map context（地圖脈絡）is generated from imported GPX checkpoint "
                "coordinates and is planning evidence only."
            ),
        },
        "features": [
            {
                "type": "Feature",
                "id": f"{project_id}.imported_golden_route_cp_corridor",
                "properties": {
                    "feature_type": "approved_corridor",
                    "name": "Imported golden route CP corridor candidate",
                    "route_level": "planning_candidate",
                    "corridor_half_width_m": 30.0,
                    "source": "pretrip_standalone_importer",
                    "source_version": IMPORTER_VERSION,
                    "confidence": 0.66,
                    "known_staleness_risk": "medium",
                },
                "geometry": {"type": "LineString", "coordinates": coordinates},
            },
            _poi_feature(project_id, "start", "Imported golden route start candidate", coordinates[0]),
            _poi_feature(project_id, "finish", "Imported golden route finish candidate", coordinates[-1]),
        ],
    }


def _poi_feature(project_id: str, role: str, name: str, coordinate: list[float]) -> dict[str, Any]:
    return {
        "type": "Feature",
        "id": f"{project_id}.imported_golden_route_{role}",
        "properties": {
            "feature_type": "poi",
            "name": name,
            "poi_type": "trailhead",
            "source": "pretrip_standalone_importer",
            "source_version": IMPORTER_VERSION,
            "confidence": 0.66,
            "known_staleness_risk": "medium",
        },
        "geometry": {"type": "Point", "coordinates": coordinate},
    }


def _build_import_manifest(
    *,
    request: PretripImportRequest,
    project_root: Path,
    primary_gpx: Path,
    reference_paths: list[Path],
    import_timestamp: str,
    output_refs: dict[str, str],
    route_summary: dict[str, Any],
    checkpoint_count: int,
    segment_count: int,
    gis_perception: dict[str, Any],
    gis_perception_ai_judgements: dict[str, Any],
    route_note_candidates: dict[str, Any],
    route_note_ln_proposals: dict[str, Any],
) -> dict[str, Any]:
    return {
        "artifact_kind": "pretrip_import_manifest",
        "schema_version": "0.1.0",
        "importer_version": IMPORTER_VERSION,
        "project_id": request.project_id,
        "profile": request.profile,
        "import_stage": request.import_stage,
        "imported_at": import_timestamp,
        "workspace_root": project_root.resolve().as_posix(),
        "network_policy": {
            "network_calls_allowed": False,
            "profile": request.profile,
            "notes": "pi-offline（Pi 離線模式）and mac-workstation import local files only in this slice.",
        },
        "inputs": {
            "golden_route_gpx": _source_record(
                primary_gpx,
                role=_golden_route_role(request),
            ),
            "reference_tracks": [
                _source_record(path, role="reference_track")
                for path in reference_paths
            ],
        },
        "outputs": output_refs,
        "counts": {
            "source_file_count": 1 + len(reference_paths),
            "golden_route_count": 1,
            "reference_track_count": len(reference_paths),
            "checkpoint_candidate_count": checkpoint_count,
            "segment_candidate_count": segment_count,
            "route_note_candidate_count": route_note_candidates["counts"]["note_candidate_count"],
            "route_note_potential_ln_signal_count": route_note_candidates["counts"][
                "potential_ln_signal_count"
            ],
            "route_note_ln_proposal_count": route_note_ln_proposals["counts"]["proposal_count"],
            "gis_perception_ai_judgement_count": gis_perception_ai_judgements[
                "judgement_count"
            ],
            "gis_perception_checkpoint_candidate_count": gis_perception["counts"][
                "checkpoint_candidate_count"
            ],
            "route_point_count": route_summary["point_count"],
        },
        "planning_semantics": _planning_semantics(request),
        "boundary": {
            "pretrip_candidate_evidence_only": True,
            "golden_route_is_reference_evidence": True,
            "actual_user_track_available": request.import_stage == "post_analysis",
            "actual_user_track_required_before_post_analysis": request.import_stage == "pretrip",
            "unwalked_route_sections_require_manual_waypoints": True,
            "unwalked_route_sections_require_danger_review": True,
            "phase1_runtime_mutation_allowed": False,
            "phase2_brain_writeback_allowed": False,
            "incident_store_mutation_allowed": False,
            "real_outbound_transport_allowed": False,
            "mission_graph_compiled": False,
            "raw_gpx_embedded_in_json": False,
        },
    }


def _build_admin_projection(
    *,
    request: PretripImportRequest,
    route_summary: dict[str, Any],
    output_refs: dict[str, str],
    reference_track_count: int,
    checkpoint_count: int,
    segment_count: int,
    gis_perception: dict[str, Any],
    gis_perception_ai_judgements: dict[str, Any],
) -> dict[str, Any]:
    return {
        "artifact_kind": "pretrip_admin_surface_projection",
        "schema_version": "0.1.0",
        "project_id": request.project_id,
        "surface_targets": ["/admin", "/admin/pretrip", "/admin/debug"],
        "projection_only": True,
        "import_stage": request.import_stage,
        "route": {
            "route_role": _golden_route_role(request),
            "route_name": route_summary["route_name"],
            "point_count": route_summary["point_count"],
            "distance_m": route_summary["distance_m"],
            "bbox_wgs84": route_summary["bbox_wgs84"],
            "route_summary_ref": output_refs["route_summary_ref"],
            "map_context_ref": output_refs["map_context_ref"],
        },
        "candidate_counts": {
            "checkpoint_candidate_count": checkpoint_count,
            "segment_candidate_count": segment_count,
            "reference_track_count": reference_track_count,
            "route_note_candidate_count": gis_perception["counts"][
                "gpx_route_note_candidate_count"
            ],
            "route_note_ln_proposal_count": gis_perception["counts"][
                "gpx_ln_proposal_count"
            ],
            "gis_perception_ai_judgement_count": gis_perception_ai_judgements[
                "judgement_count"
            ],
            "gis_perception_checkpoint_candidate_count": gis_perception["counts"][
                "checkpoint_candidate_count"
            ],
        },
        "gis_perception": {
            "source_profile": gis_perception["source_profile"],
            "status": gis_perception["status"],
            "counts": gis_perception["counts"],
            "classifier": gis_perception["classifier"],
            "boundary": gis_perception["boundary"],
            "ai_judgements": {
                "artifact_kind": gis_perception_ai_judgements["artifact_kind"],
                "provider_kind": gis_perception_ai_judgements["provider_kind"],
                "model_name": gis_perception_ai_judgements["model_name"],
                "prompt_sha256": gis_perception_ai_judgements["prompt_sha256"],
                "input_count": gis_perception_ai_judgements["input_count"],
                "judgement_count": gis_perception_ai_judgements["judgement_count"],
                "live_model_call_performed": gis_perception_ai_judgements[
                    "live_model_call_performed"
                ],
                "network_calls_allowed": gis_perception_ai_judgements[
                    "network_calls_allowed"
                ],
            },
            "gis_perception_candidates_ref": output_refs["gis_perception_candidates_ref"],
            "gis_perception_ai_judgements_ref": output_refs[
                "gis_perception_ai_judgements_ref"
            ],
            "route_note_candidates_ref": output_refs["route_note_candidates_ref"],
            "route_note_ln_proposals_ref": output_refs["route_note_ln_proposals_ref"],
        },
        "pretrip_surface": {
            "project_ref": "project.json",
            "package_ref": output_refs["package_ref"],
            "import_manifest_ref": output_refs["import_manifest_ref"],
        },
        "after_action_surface": {
            "after_action_style_projection": True,
            "completed_mission_replay": False,
            "incident_package_source": False,
            "pretrip_actual_user_track_available": request.import_stage == "post_analysis",
            "pretrip_golden_route_replacement_expected_after_return": (
                request.import_stage == "pretrip"
            ),
            "notes": (
                "/admin can inspect this imported route as map-first planning evidence, "
                "not as completed mission evidence."
            ),
        },
        "planning_semantics": _planning_semantics(request),
        "debug_surface": {
            "debug_projection_events_ref": output_refs["debug_projection_events_ref"],
            "file_runtime_debug_log_compatible": True,
            "live_runtime_events": False,
        },
        "boundary": _projection_boundary(),
    }


def _build_debug_projection_events(
    *,
    request: PretripImportRequest,
    import_timestamp: str,
    route_summary: dict[str, Any],
    reference_track_count: int,
    checkpoint_count: int,
    segment_count: int,
    gis_perception: dict[str, Any],
    gis_perception_ai_judgements: dict[str, Any],
) -> list[dict[str, Any]]:
    session_id = f"debug_session.pretrip_import.{request.project_id}"
    base_payload = {
        "project_id": request.project_id,
        "profile": request.profile,
        "import_stage": request.import_stage,
        "route_role": _golden_route_role(request),
        "projection_only": True,
        "planning_semantics": _planning_semantics(request),
        "boundary": _projection_boundary(),
    }
    events = [
        RuntimeDebugEvent(
            event_id=f"debug_event.pretrip_import.{request.project_id}.000001",
            session_id=session_id,
            timestamp=import_timestamp,
            sequence=1,
            kind="debug_session_started",
            source="pretrip_import",
            phase="phase35",
            severity="info",
            subject_ref=request.project_id,
            summary="Pretrip import projection started.",
            payload=base_payload,
        ),
        RuntimeDebugEvent(
            event_id=f"debug_event.pretrip_import.{request.project_id}.000002",
            session_id=session_id,
            timestamp=import_timestamp,
            sequence=2,
            kind="provider_status_recorded",
            source="pretrip_import",
            phase="phase35",
            severity="info",
            subject_ref=request.project_id,
            summary="Local GPX import sources were inspected.",
            payload={
                **base_payload,
                "provider": "local_gpx_corpus",
                "gis_perception_provider": gis_perception_ai_judgements[
                    "provider_kind"
                ],
                "gis_perception_model_name": gis_perception_ai_judgements[
                    "model_name"
                ],
                "gis_perception_prompt_sha256": gis_perception_ai_judgements[
                    "prompt_sha256"
                ],
                "golden_route_count": 1,
                "reference_track_count": reference_track_count,
                "network_calls_allowed": False,
            },
        ),
        RuntimeDebugEvent(
            event_id=f"debug_event.pretrip_import.{request.project_id}.000003",
            session_id=session_id,
            timestamp=import_timestamp,
            sequence=3,
            kind="progress_update_recorded",
            source="pretrip_import",
            phase="phase35",
            severity="info",
            subject_ref=request.project_id,
            summary="Pretrip route candidates were generated.",
            payload={
                **base_payload,
                "route_point_count": route_summary["point_count"],
                "distance_m": route_summary["distance_m"],
                "checkpoint_candidate_count": checkpoint_count,
                "segment_candidate_count": segment_count,
                "route_note_candidate_count": gis_perception["counts"][
                    "gpx_route_note_candidate_count"
                ],
                "route_note_ln_proposal_count": gis_perception["counts"][
                    "gpx_ln_proposal_count"
                ],
                "gis_perception_ai_judgement_count": gis_perception_ai_judgements[
                    "judgement_count"
                ],
                "gis_perception_checkpoint_candidate_count": gis_perception["counts"][
                    "checkpoint_candidate_count"
                ],
            },
        ),
        RuntimeDebugEvent(
            event_id=f"debug_event.pretrip_import.{request.project_id}.000004",
            session_id=session_id,
            timestamp=import_timestamp,
            sequence=4,
            kind="debug_session_completed",
            source="pretrip_import",
            phase="phase35",
            severity="info",
            subject_ref=request.project_id,
            summary="Pretrip import projection completed.",
            payload={
                **base_payload,
                "safety_level": "L0_NORMAL",
                "observations_processed": route_summary["point_count"],
                "mission_graph_compiled": False,
                "actual_user_track_available": request.import_stage == "post_analysis",
            },
        ),
    ]
    return [event.model_dump(mode="json") for event in events]


def _projection_boundary() -> dict[str, bool]:
    return {
        "projection_only": True,
        "golden_route_is_reference_evidence": True,
        "phase1_runtime_mutation_allowed": False,
        "phase2_brain_writeback_allowed": False,
        "incident_store_mutation_allowed": False,
        "real_outbound_transport_allowed": False,
        "mission_graph_compiled": False,
    }


def _source_record(path: Path, *, role: str) -> dict[str, Any]:
    stat = path.stat()
    return {
        "role": role,
        "uri": path.resolve().as_posix(),
        "sha256": sha256_file(path),
        "size_bytes": stat.st_size,
    }


def _golden_route_role(request: PretripImportRequest) -> str:
    if request.import_stage == "post_analysis":
        return "actual_track_replacing_pretrip_golden_route"
    return "golden_route_reference"


def _planning_semantics(request: PretripImportRequest) -> dict[str, Any]:
    return {
        "golden_route": {
            "meaning": (
                "selected similar reference route before departure"
                if request.import_stage == "pretrip"
                else "actual walked route replacing the pretrip golden route"
            ),
            "actual_user_track": request.import_stage == "post_analysis",
            "runtime_safety_truth": False,
        },
        "pretrip_actual_user_track_exists": request.import_stage == "post_analysis",
        "manual_waypoint_route_policy": {
            "unwalked_route_sections_allowed": True,
            "manual_waypoints_required": True,
            "danger_review_required": True,
            "notes": (
                "Unwalked route sections（未曾發生的路徑區段）can be planned only "
                "through manually drawn waypoint candidates and must raise danger review."
            ),
        },
        "post_analysis_replacement_policy": {
            "actual_track_may_replace_pretrip_golden_route": True,
            "historical_planning_evidence_mutation_allowed": False,
        },
    }


def _project_payload(
    *,
    project_root: Path,
    project_id: str,
    output_refs: dict[str, str],
    route_summary: dict[str, Any],
    reference_track_count: int,
    checkpoint_count: int,
    segment_count: int,
    gis_perception: dict[str, Any],
    gis_perception_ai_judgements: dict[str, Any],
    import_stage: ImportStage,
) -> dict[str, Any]:
    project_path = project_root / "project.json"
    payload: dict[str, Any] = {}
    if project_path.exists():
        payload = json.loads(project_path.read_text(encoding="utf-8"))
    payload.update(
        {
            "project_id": project_id,
            "route_name": route_summary["route_name"],
            "import_profile": "standalone_pretrip_importer",
            "import_stage": import_stage,
            "route_role": "golden_route",
            "actual_user_track_available": import_stage == "post_analysis",
            "importer_version": IMPORTER_VERSION,
            **output_refs,
            "source_artifact_count": 1 + reference_track_count,
            "checkpoint_candidate_count": checkpoint_count,
            "segment_candidate_count": segment_count,
            "route_note_candidate_count": gis_perception["counts"][
                "gpx_route_note_candidate_count"
            ],
            "route_note_potential_ln_signal_count": gis_perception["counts"][
                "gpx_potential_ln_signal_count"
            ],
            "route_note_ln_proposal_count": gis_perception["counts"]["gpx_ln_proposal_count"],
            "gis_perception_ai_judgement_count": gis_perception_ai_judgements[
                "judgement_count"
            ],
            "gis_perception_checkpoint_candidate_count": gis_perception["counts"][
                "checkpoint_candidate_count"
            ],
            "map_corridor_candidate_count": 1,
            "map_hazard_candidate_count": 0,
            "map_poi_candidate_count": 2,
            "reference_track_count": reference_track_count,
        }
    )
    return payload


def _write_jsonl(path: Path, events: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(
            json.dumps(event, separators=(",", ":"), sort_keys=True) + "\n"
            for event in events
        ),
        encoding="utf-8",
    )


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


if __name__ == "__main__":
    main()
