from __future__ import annotations

from typing import Any


ORDERING_POLICY = "wmts_tiles_bottom_api_top"

SCOUT_LAYER_CONTRACT: tuple[dict[str, Any], ...] = (
    {
        "layer_id": "imagery",
        "label": "Imagery",
        "label_zh": "影像圖層（WMTS，最底層）",
        "layer_kind": "imagery",
        "z_index": 0,
        "render_mode": "wmts_raster_tile",
        "source_kind": "wmts_tile",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Optional national imagery basemap, rendered at the bottom and never used as runtime safety truth.",
        "components": ("admin_map_layers.py", "docs/admin/phase4-pretrip-planning.html", "docs/admin/phase-3-5-runtime-debug.html", "docs/admin/phase1-after-action.html", "admin_imagery_sources.py"),
        "dependencies": "WMTS source registry; may require network or seeded cache.",
        "states": "Available even when workspace evidence is absent; runtime fetch failures must not blank vector evidence.",
        "verification": "Static layer contract plus browser toggle/render-group smoke check.",
    },
    {
        "layer_id": "rudy",
        "label": "Rudy",
        "label_zh": "魯地圖圖層（Rudy Map，登山地形底圖）",
        "layer_kind": "imagery",
        "z_index": 4,
        "render_mode": "wmts_raster_tile",
        "source_kind": "wmts_kvp_tile",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Optional Rudy hiking basemap overlay for pretrip inspection.",
        "components": ("admin_map_layers.py", "docs/admin/*.html", "admin_imagery_sources.py"),
        "dependencies": "Rudy WMTS source entry and cache TTL policy.",
        "states": "Unchecked by default; failures are isolated from OSM/vector layers.",
        "verification": "Source id, control, rank, group, and browser toggle checks.",
    },
    {
        "layer_id": "rudy-twmap",
        "label": "Rudy+TW",
        "label_zh": "魯地圖加 TWMap 樣式圖層（Rudy Map + TWMap）",
        "layer_kind": "imagery",
        "z_index": 4,
        "render_mode": "wmts_raster_tile",
        "source_kind": "wmts_kvp_tile",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Optional Rudy+TW raster layer and preferred OCR source for trail mileage labels.",
        "components": ("admin_map_layers.py", "admin_imagery_sources.py", "pretrip_raster_label_ocr.py"),
        "dependencies": "Seeded Rudy+TW tiles before OCR; OCR output must pass through raster label adapter.",
        "states": "Can be disabled visually while remaining a map-preparation OCR source.",
        "verification": "Layer contract, source id, OCR plan/source checks, and browser toggle.",
    },
    {
        "layer_id": "relief",
        "label": "Relief",
        "label_zh": "彩色地形陰影圖層（color relief terrain shading）",
        "layer_kind": "terrain",
        "z_index": 4,
        "render_mode": "wmts_raster_tile",
        "source_kind": "wmts_kvp_tile",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Optional color relief raster reference, separate from Scout terrain visualization.",
        "components": ("admin_map_layers.py", "admin_imagery_sources.py", "docs/admin/*.html"),
        "dependencies": "Happyman relief WMTS source.",
        "states": "Unchecked by default; no workspace artifact required.",
        "verification": "Control/rank/source/group contract and browser toggle.",
    },
    {
        "layer_id": "geology",
        "label": "Geology",
        "label_zh": "地質圖圖層（geology overlay，規劃證據）",
        "layer_kind": "terrain",
        "z_index": 4,
        "render_mode": "wmts_raster_tile",
        "source_kind": "wmts_kvp_tile",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Optional geology context overlay, candidate evidence only.",
        "components": ("admin_map_layers.py", "admin_imagery_sources.py", "docs/admin/*.html"),
        "dependencies": "Geology WMTS source and cache.",
        "states": "Unchecked by default; network/cache failure must not hide route evidence.",
        "verification": "Control/rank/source/group contract and browser toggle.",
    },
    {
        "layer_id": "topo-5k",
        "label": "Topo 5K",
        "label_zh": "五千分之一地形圖圖層（1/5000 topo map）",
        "layer_kind": "terrain",
        "z_index": 4,
        "render_mode": "wmts_raster_tile",
        "source_kind": "wmts_kvp_tile",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Optional 1/5000 topographic reference overlay for map review.",
        "components": ("admin_map_layers.py", "admin_imagery_sources.py", "docs/admin/*.html"),
        "dependencies": "Topo WMTS source and cache.",
        "states": "Unchecked by default; must stay visually below Scout evidence overlays.",
        "verification": "Control/rank/source/group contract and browser toggle.",
    },
    {
        "layer_id": "forest",
        "label": "Forest",
        "label_zh": "林班界圖層（forest compartment overlay）",
        "layer_kind": "terrain",
        "z_index": 4,
        "render_mode": "wmts_raster_tile",
        "source_kind": "wmts_kvp_tile",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Optional forest compartment overlay, candidate context only.",
        "components": ("admin_map_layers.py", "admin_imagery_sources.py", "docs/admin/*.html"),
        "dependencies": "Forest WMTS source and cache.",
        "states": "Unchecked by default; no runtime mutation.",
        "verification": "Control/rank/source/group contract and browser toggle.",
    },
    {
        "layer_id": "osm",
        "label": "OSM",
        "label_zh": "OSM 底圖（OpenStreetMap 開放街圖）",
        "layer_kind": "basemap",
        "z_index": 8,
        "render_mode": "osm_raster_tile",
        "source_kind": "openstreetmap_tile",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "OSM/local XYZ basemap above raster imagery and below Scout evidence.",
        "components": ("admin_map_layers.py", "admin_basemap_tiles.py", "docs/admin/*.html", "pretrip_layer_preparation.py"),
        "dependencies": "Local tile proxy or network fetch during map preparation.",
        "states": "Tile fallback may reuse parent/cached tiles at high zoom; never blank the viewport.",
        "verification": "Layer prep manifest, control/rank/group checks, and browser zoom/toggle smoke.",
    },
    {
        "layer_id": "terrain",
        "label": "Terrain",
        "label_zh": "地形視覺化圖層（DEM/DTM hillshade/tint/slope/contours）",
        "layer_kind": "terrain",
        "z_index": 20,
        "render_mode": "svg_backdrop",
        "source_kind": "terrain_visualization",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "DEM/DTM terrain visualization evidence: hillshade, elevation tint, slope shading, and contours.",
        "components": ("pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "DEM/DTM source or fixture; normalized terrain artifacts and tile refs.",
        "states": "Missing DEM yields unavailable/partial evidence, not a runtime safety truth.",
        "verification": "Preparation layer ready check, artifact count/hash check, group/rank/browser toggle.",
    },
    {
        "layer_id": "corridors",
        "label": "Corridors",
        "label_zh": "路廊圖層（可通行路徑脈絡）",
        "layer_kind": "evidence",
        "z_index": 40,
        "render_mode": "svg_overlay",
        "source_kind": "map_context",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Route corridor evidence used for map context, below route and review targets.",
        "components": ("pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Map candidates/context artifacts.",
        "states": "May be unavailable when no context source exists; should not block core route display.",
        "verification": "Source ref, rank, group, and browser toggle checks.",
    },
    {
        "layer_id": "overpass",
        "label": "Overpass",
        "label_zh": "Overpass 向量證據圖層（OSM corridor/POI/hazard evidence）",
        "layer_kind": "evidence",
        "z_index": 42,
        "render_mode": "svg_overlay",
        "source_kind": "overpass_vector_evidence",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Overpass vector evidence used as route-center truth for pretrip candidate geometry.",
        "components": ("pretrip_layer_preparation.py", "pretrip_overpass_route_alignment.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Network fetch during explicit preparation or fixture; no live runtime safety call.",
        "states": "If absent, GPX geometry remains candidate-only and alignment confidence must reflect that.",
        "verification": "Preparation ready/source refs, projection alignment, group/rank/browser toggle.",
    },
    {
        "layer_id": "route",
        "label": "Route",
        "label_zh": "路線軌跡圖層",
        "layer_kind": "evidence",
        "z_index": 44,
        "render_mode": "svg_overlay",
        "source_kind": "route_fixture",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Reviewed/pretrip route line, preferably Overpass-aligned and not raw golden GPX when alignment is available.",
        "components": ("pretrip_import.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Filtered GPX and optional Overpass projection.",
        "states": "If Overpass cannot acceptably project, retain GPX fallback with provenance and confidence.",
        "verification": "Route point/count/source check, rank/group/browser toggle, alignment metadata check.",
    },
    {
        "layer_id": "completed-track",
        "label": "Completed track",
        "label_zh": "完成旅程 GPX 圖層（post-analysis only）",
        "layer_kind": "evidence",
        "z_index": 45,
        "render_mode": "svg_overlay",
        "source_kind": "completed_trip_track",
        "default_enabled": True,
        "surfaces": ("after-action",),
        "required_behavior": "After-action active completed trip GPX track, not shown as pretrip route truth.",
        "components": ("post_analysis_completed_trip_recordings.py", "admin_map_layers.py", "docs/admin/phase1-after-action.html"),
        "dependencies": "Selected completed-trip recording projection.",
        "states": "Absent before post-analysis selection; only after-action surface requires a control.",
        "verification": "After-action control/group/rank and completed-track source availability checks.",
    },
    {
        "layer_id": "reference-tracks",
        "label": "Reference tracks",
        "label_zh": "參考軌跡圖層（專家/山友 GPX）",
        "layer_kind": "evidence",
        "z_index": 46,
        "render_mode": "svg_overlay",
        "source_kind": "reference_track",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Reference GPX tracks, preserving trk/trkseg boundaries to avoid artificial straight lines.",
        "components": ("pretrip_import.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Filtered reference GPX display geometry with coordinate_segments.",
        "states": "Can be hidden to reduce visual clutter; never overrides reviewed route geometry.",
        "verification": "coordinate_segments source, rank/group/browser toggle.",
    },
    {
        "layer_id": "retreat",
        "label": "Retreat",
        "label_zh": "撤退/折返路線圖層",
        "layer_kind": "evidence",
        "z_index": 48,
        "render_mode": "svg_overlay",
        "source_kind": "planning_candidate",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Retreat and turnaround planning candidates, not runtime autonomous actions.",
        "components": ("pretrip_import.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Retreat route candidates if available.",
        "states": "May be unavailable; UI control must still exist for consistent layer set.",
        "verification": "Control/source availability/rank/group/browser toggle.",
    },
    {
        "layer_id": "segments",
        "label": "Segments",
        "label_zh": "分段圖層",
        "layer_kind": "evidence",
        "z_index": 50,
        "render_mode": "svg_overlay",
        "source_kind": "planning_candidate",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Route segments generated from filtered/aligned route, with reasonable stroke width at high zoom.",
        "components": ("pretrip_import.py", "pretrip_overpass_route_alignment.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Checkpoint sequence and route geometry.",
        "states": "Resume/coarse GPX gaps must be flagged, not silently treated as precise geometry.",
        "verification": "Segment count/source/alignment metadata, rank/group/browser toggle.",
    },
    {
        "layer_id": "risk-ribbon",
        "label": "Risk ribbon",
        "label_zh": "路徑風險色帶（Route Risk Ribbon，沿路徑分段顯示風險）",
        "layer_kind": "evidence",
        "z_index": 54,
        "render_mode": "svg_overlay",
        "source_kind": "scout_risk_engine",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Baseline route risk ribbon, pretrip candidate evidence only.",
        "components": ("pretrip_risk_heatmap.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Risk engine output and route-aligned samples.",
        "states": "Unavailable if risk artifacts missing; must not be replaced by calibrated heatmap.",
        "verification": "Risk artifact count/source, rank/group/browser toggle.",
    },
    {
        "layer_id": "risk-heatmap",
        "label": "Risk calibration",
        "label_zh": "風險校準熱區圖層（Calibrated Heat Map，本 workspace 相對熱區）",
        "layer_kind": "evidence",
        "z_index": 55,
        "render_mode": "svg_overlay",
        "source_kind": "scout_risk_engine",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Calibrated risk heatmap layer distinct from baseline risk ribbon.",
        "components": ("pretrip_risk_heatmap.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Baseline risk samples and calibration output.",
        "states": "Missing calibrated output must be surfaced as unavailable instead of silently disappearing.",
        "verification": "Calibrated artifact count/source, rank/group/browser toggle.",
    },
    {
        "layer_id": "risk-delta",
        "label": "Risk delta",
        "label_zh": "風險差異圖層（Delta，比對 baseline 與 calibrated heat）",
        "layer_kind": "evidence",
        "z_index": 56,
        "render_mode": "svg_overlay",
        "source_kind": "scout_risk_engine",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Difference layer between baseline and calibrated risk evidence.",
        "components": ("pretrip_risk_heatmap.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Both baseline and calibrated risk artifacts.",
        "states": "Disabled by default; if inputs are absent, unavailable with provenance.",
        "verification": "Delta source or paired-source ref, rank/group/browser toggle.",
    },
    {
        "layer_id": "soil-moisture",
        "label": "Soil moisture",
        "label_zh": "土壤含水量圖層（SMAP/GEE hydrology context）",
        "layer_kind": "environment",
        "z_index": 57,
        "render_mode": "svg_overlay",
        "source_kind": "gee_soil_moisture_candidate",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "GEE/SMAP soil moisture context, candidate environmental evidence only.",
        "components": ("scout_gee_integration.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Optional GEE/SMAP fetch or fixture-backed points.",
        "states": "Unavailable when GEE credentials/data are absent; no safety truth mutation.",
        "verification": "Contract source availability, rank/group/browser toggle.",
    },
    {
        "layer_id": "antecedent-rain",
        "label": "Antecedent rain",
        "label_zh": "前期累積降雨圖層（GPM IMERG hydrology context）",
        "layer_kind": "environment",
        "z_index": 58,
        "render_mode": "svg_overlay",
        "source_kind": "gee_antecedent_rain_candidate",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "GEE/GPM antecedent rain context, candidate environmental evidence only.",
        "components": ("scout_gee_integration.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Optional GEE/GPM fetch or fixture-backed points.",
        "states": "Unavailable when data are absent; no runtime safety truth.",
        "verification": "Contract source availability, rank/group/browser toggle.",
    },
    {
        "layer_id": "cwa-qpf",
        "label": "CWA QPE / QPF",
        "label_zh": "定量降水圖層（CWA 過去 1 小時 QPE／未來 1 小時 QPF 路線格點）",
        "layer_kind": "environment",
        "z_index": 59,
        "render_mode": "geojson_overlay",
        "source_kind": "cwa_qpf_candidate",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "CWA quantitative precipitation forecast grid/timeline evidence, candidate-only and review-gated.",
        "components": ("scout_weather_integration.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Prepared CWA QPE/QPF numeric grids, route projection, and legacy QPF artifacts from explicit server weather preparation.",
        "states": "Unavailable until CWA rainfall artifacts are prepared; provider no-data must remain unknown rather than zero.",
        "verification": "Preparation source ref, rank/group/browser toggle, and no client API key exposure.",
    },
    {
        "layer_id": "risk-score",
        "label": "Risk score",
        "label_zh": "風險分數圖層（Scout Risk Engine 候選分數）",
        "layer_kind": "evidence",
        "z_index": 60,
        "render_mode": "svg_overlay",
        "source_kind": "scout_risk_engine",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Point risk-score evidence, distinct from ribbon/heatmap/delta.",
        "components": ("pretrip_risk_heatmap.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Risk point output from terrain/risk engine.",
        "states": "Off by default; candidate-only evidence.",
        "verification": "Risk point artifact/source/count, rank/group/browser toggle.",
    },
    {
        "layer_id": "checkpoints",
        "label": "Checkpoints",
        "label_zh": "CP 檢查點圖層",
        "layer_kind": "evidence",
        "z_index": 62,
        "render_mode": "svg_overlay",
        "source_kind": "planning_candidate",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "CP candidates/reviewed checkpoints aligned to route evidence when possible.",
        "components": ("pretrip_import.py", "pretrip_overpass_route_alignment.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Route segmentation and candidate review state.",
        "states": "Marker radius must stay screen-sized at high zoom; focus target uses 1km box unless otherwise specified.",
        "verification": "CP count/source/alignment metadata, rank/group/browser toggle and focus smoke.",
    },
    {
        "layer_id": "pois",
        "label": "POI",
        "label_zh": "POI 興趣點/關鍵地點圖層",
        "layer_kind": "evidence",
        "z_index": 64,
        "render_mode": "svg_overlay",
        "source_kind": "map_context",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Named POI/context candidates with human-readable labels.",
        "components": ("pretrip_route_context_collection.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Route context collection and named-point synthesis.",
        "states": "Avoid raw variable names in labels; unavailable is allowed if no POI evidence exists.",
        "verification": "Label/source/group/rank/browser toggle checks.",
    },
    {
        "layer_id": "hazards",
        "label": "Hazards",
        "label_zh": "危險地形/風險圖層",
        "layer_kind": "evidence",
        "z_index": 65,
        "render_mode": "svg_overlay",
        "source_kind": "map_context",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Hazard candidates from terrain, context, route notes, OCR, or external evidence.",
        "components": ("pretrip_route_context_collection.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Hazard context sources; not safety truth.",
        "states": "Needs provenance/source and review status before being used in reviewed plan.",
        "verification": "Source/group/rank/browser toggle checks.",
    },
    {
        "layer_id": "route-notes",
        "label": "Route notes",
        "label_zh": "山友註記/路況經驗圖層",
        "layer_kind": "evidence",
        "z_index": 66,
        "render_mode": "svg_overlay",
        "source_kind": "route_note_candidate",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Historical/public route notes as candidate context, not direct MCP/Boss truth.",
        "components": ("pretrip_import.py", "pretrip_route_context_collection.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "GPX waypoint notes or route context collection.",
        "states": "Can seed web/context collection; detailed low-signal notes should not flood MCP/Boss.",
        "verification": "Source/count/group/rank/browser toggle checks.",
    },
    {
        "layer_id": "cwa-weather",
        "label": "CWA weather",
        "label_zh": "中央氣象署天氣圖層（警特報/觀測/預報，候選證據）",
        "layer_kind": "environment",
        "z_index": 67,
        "render_mode": "geojson_overlay",
        "source_kind": "cwa_weather_candidate",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "CWA warnings, observations, forecast timeline, astronomy, tide, earthquake, station background, and cached temporal radar/satellite child overlays with independent opacity/timeline controls.",
        "components": ("scout_weather_integration.py", "cwa_imagery_registry.py", "cwa_radar_ingestor.py", "cwa_satellite_ingestor.py", "weather_imagery_tile_cache.py", "route_imagery_sampler.py", "radar_motion_estimator.py", "radar_satellite_risk_extractor.py", "pretrip_weather_decision_collection.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Prepared CWA weather artifacts; server-side SCOUT_CWA_API_KEY only.",
        "states": "Unavailable when CWA artifacts are missing; status and source refs must not expose secrets. Radar/satellite processing runs server-side only; Pi/mobile consume compact JSON and cached display assets.",
        "verification": "Weather evidence source refs, rank/group/browser toggle, nested radar/satellite opacity and 3/6/9/12h timeline controls, cache-only asset delivery, and candidate-only boundary.",
    },
    {
        "layer_id": "mcp",
        "label": "MCP",
        "label_zh": "MCP 主要關鍵點圖層",
        "layer_kind": "evidence",
        "z_index": 68,
        "render_mode": "svg_overlay",
        "source_kind": "major_critical_point_candidate",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Major critical point candidates synthesized from representative evidence, with spacing and provenance.",
        "components": ("pretrip_route_context_collection.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Route context, CP/risk/evidence grouping, and optional OCR mileage anchors.",
        "states": "MCP count may be zero only with explicit unavailable reason; otherwise preserve existing refs during preparation.",
        "verification": "MCP count/source/alignment metadata, rank/group/browser toggle.",
    },
    {
        "layer_id": "boss-points",
        "label": "Boss points",
        "label_zh": "魔王點 Challenge Fit 圖層",
        "layer_kind": "evidence",
        "z_index": 70,
        "render_mode": "svg_overlay",
        "source_kind": "pretrip_boss_point_challenge_fit",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Route Boss Demand vs User Pace/Energy Reserve challenge fit points, derived from pressure peaks plus named/review evidence.",
        "components": ("pretrip_boss_point_synthesis.py", "pretrip_layer_preparation.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Route pressure profile, Overpass-aligned geometry, MCP/named evidence, and energy reserve model.",
        "states": "Must not classify rest areas as Boss solely because users stop there; candidate-only evidence.",
        "verification": "Boss count/source/route-distance metadata, rank/group/browser toggle and highlight smoke.",
    },
    {
        "layer_id": "events",
        "label": "Ln events",
        "label_zh": "Ln 安全事件圖層",
        "layer_kind": "evidence",
        "z_index": 72,
        "render_mode": "svg_overlay",
        "source_kind": "runtime_evidence",
        "default_enabled": True,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Planned or replayed Ln/action/event evidence, never a direct live safety trigger in pretrip.",
        "components": ("admin_evidence_timeline.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Debug projection or completed trip event replay.",
        "states": "Absent in pure pretrip is allowed; visible in debug/after-action replay.",
        "verification": "Event source availability, rank/group/browser toggle.",
    },
    {
        "layer_id": "weather-api",
        "label": "Weather API",
        "label_zh": "氣象 API 圖層（最上層）",
        "layer_kind": "api",
        "z_index": 80,
        "render_mode": "api_overlay",
        "source_kind": "weather_api_reference",
        "default_enabled": False,
        "surfaces": ("pretrip", "debug", "after-action"),
        "required_behavior": "Weather API status/context overlay, explicitly marked as external API evidence.",
        "components": ("admin_weather_overlay.py", "admin_map_layers.py", "docs/admin/*.html"),
        "dependencies": "Optional configured weather provider; no hidden network call in tests.",
        "states": "Unavailable when credentials/provider missing; UI should show status not crash.",
        "verification": "Weather source/status contract, rank/group/browser toggle.",
    },
)

SCOUT_LAYER_IDS = tuple(layer["layer_id"] for layer in SCOUT_LAYER_CONTRACT)
SCOUT_LAYER_RANKS = {str(layer["layer_id"]): int(layer["z_index"]) for layer in SCOUT_LAYER_CONTRACT}
SCOUT_LAYER_CONTRACT_BY_ID = {str(layer["layer_id"]): layer for layer in SCOUT_LAYER_CONTRACT}
SCOUT_SURFACE_LAYER_IDS = {
    surface: tuple(
        str(layer["layer_id"])
        for layer in SCOUT_LAYER_CONTRACT
        if surface in layer["surfaces"]
    )
    for surface in ("pretrip", "debug", "after-action")
}

SCOUT_PREPARATION_LAYER_IDS = (
    "imagery",
    "osm",
    "overpass",
    "terrain",
    "risk-score",
    "risk-ribbon",
    "risk-heatmap",
    "risk-delta",
    "cwa-qpf",
    "soil-moisture",
    "antecedent-rain",
    "cwa-weather",
    "weather",
    "reference-tracks",
    "route",
    "segments",
    "checkpoints",
    "mcp",
    "pois",
    "hazards",
    "corridors",
    "retreat",
    "route-notes",
)

SCOUT_LAYER_HTML_FILES = {
    "pretrip": "docs/admin/phase4-pretrip-planning.html",
    "debug": "docs/admin/phase-3-5-runtime-debug.html",
    "after-action": "docs/admin/phase1-after-action.html",
}
