from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from scout_gee_integration import GEE_ENVIRONMENT_DATASETS


GEE_ENVIRONMENT_TOOL_ID = "scout.ai.gee_environment.assess.v0"
GEE_ENVIRONMENT_OUTPUT_KIND = "scout_ai_gee_environment_tool_output"
GEE_ENVIRONMENT_REQUIRED_FIELDS = ("project_root",)
GEE_ENVIRONMENT_OPTIONAL_FIELDS = (
    "environment_package_path",
    "factor_matrix_path",
    "go_no_go_review_path",
    "smap_timeseries_path",
    "smap_corridor_summary_path",
    "soil_moisture_grid_path",
    "gpm_raw_summary_path",
    "gpm_timeseries_path",
    "gpm_corridor_summary_path",
    "antecedent_rain_grid_path",
    "include_grid",
    "include_timeseries",
    "stale_after_hours",
)

DEFAULT_STALE_AFTER_HOURS = 24.0
DEFAULT_RESULT_LIMIT = 6
MAX_RESULT_LIMIT = 12


def assess_scout_gee_environment(
    project_root: Path | str,
    *,
    query: str = "",
    environment_package_path: str | None = None,
    factor_matrix_path: str | None = None,
    go_no_go_review_path: str | None = None,
    smap_timeseries_path: str | None = None,
    smap_corridor_summary_path: str | None = None,
    soil_moisture_grid_path: str | None = None,
    gpm_raw_summary_path: str | None = None,
    gpm_timeseries_path: str | None = None,
    gpm_corridor_summary_path: str | None = None,
    antecedent_rain_grid_path: str | None = None,
    include_grid: bool | str | None = None,
    include_timeseries: bool | str | None = None,
    stale_after_hours: float | int | str | None = None,
    limit: int = DEFAULT_RESULT_LIMIT,
) -> dict[str, Any]:
    """Read prepared GEE SMAP/GPM environment evidence from a Scout workspace.

    The tool does not initialize Earth Engine or access live GEE credentials.
    It only summarizes bounded artifacts generated by explicit pretrip map
    preparation.
    """

    root = Path(project_root)
    project = _load_json_object(root / "project.json")
    project_id = str(project.get("project_id") or project.get("id") or root.name)
    resolved_limit = _bounded_limit(limit)
    include_grid_rows = _bool_value(include_grid, default=True)
    include_timeseries_rows = _bool_value(include_timeseries, default=True)
    stale_hours = _float_or_default(
        stale_after_hours,
        default=DEFAULT_STALE_AFTER_HOURS,
    )

    source_report: list[dict[str, Any]] = []
    environment_package = _load_artifact(
        root,
        project,
        explicit_path=environment_package_path,
        ref_keys=("environment_evidence_package_ref",),
        fallbacks=("outputs/environment/environment_evidence_package.json",),
        source_kind="environment_evidence_package",
        source_report=source_report,
    )
    factor_matrix = _load_artifact(
        root,
        project,
        explicit_path=factor_matrix_path,
        ref_keys=("environment_factor_matrix_ref",),
        fallbacks=("outputs/environment/environment_factor_matrix.json",),
        source_kind="environment_factor_matrix",
        source_report=source_report,
    )
    go_no_go_review = _load_artifact(
        root,
        project,
        explicit_path=go_no_go_review_path,
        ref_keys=("go_no_go_review_draft_ref",),
        fallbacks=("outputs/environment/go_no_go_review_draft.json",),
        source_kind="go_no_go_review_draft",
        source_report=source_report,
    )
    smap_timeseries = _load_artifact(
        root,
        project,
        explicit_path=smap_timeseries_path,
        ref_keys=("gee_smap_l4_timeseries_ref",),
        fallbacks=("outputs/environment/gee/smap_l4_timeseries.json",),
        source_kind="gee_smap_l4_timeseries",
        source_report=source_report,
    )
    smap_corridor_summary = _load_artifact(
        root,
        project,
        explicit_path=smap_corridor_summary_path,
        ref_keys=("gee_smap_l4_corridor_summary_ref",),
        fallbacks=("outputs/environment/gee/smap_l4_corridor_summary.json",),
        source_kind="gee_smap_l4_corridor_summary",
        source_report=source_report,
    )
    soil_moisture_grid = _load_artifact(
        root,
        project,
        explicit_path=soil_moisture_grid_path,
        ref_keys=("gee_soil_moisture_grid_ref",),
        fallbacks=("outputs/environment/gee/soil_moisture_grid.geojson",),
        source_kind="gee_soil_moisture_grid",
        source_report=source_report,
    )
    gpm_raw_summary = _load_artifact(
        root,
        project,
        explicit_path=gpm_raw_summary_path,
        ref_keys=("gee_gpm_imerg_raw_summary_ref",),
        fallbacks=("outputs/environment/gee/gpm_imerg_raw_summary.json",),
        source_kind="gee_gpm_imerg_raw_summary",
        source_report=source_report,
    )
    gpm_timeseries = _load_artifact(
        root,
        project,
        explicit_path=gpm_timeseries_path,
        ref_keys=("gee_gpm_imerg_timeseries_ref",),
        fallbacks=("outputs/environment/gee/gpm_imerg_timeseries.json",),
        source_kind="gee_gpm_imerg_timeseries",
        source_report=source_report,
    )
    gpm_corridor_summary = _load_artifact(
        root,
        project,
        explicit_path=gpm_corridor_summary_path,
        ref_keys=("gee_gpm_imerg_corridor_summary_ref",),
        fallbacks=("outputs/environment/gee/gpm_imerg_corridor_summary.json",),
        source_kind="gee_gpm_imerg_corridor_summary",
        source_report=source_report,
    )
    antecedent_rain_grid = _load_artifact(
        root,
        project,
        explicit_path=antecedent_rain_grid_path,
        ref_keys=("gee_antecedent_rain_grid_ref",),
        fallbacks=("outputs/environment/gee/antecedent_rain_grid.geojson",),
        source_kind="gee_antecedent_rain_grid",
        source_report=source_report,
    )

    artifacts = {
        "environment_package": environment_package,
        "factor_matrix": factor_matrix,
        "go_no_go_review": go_no_go_review,
        "smap_timeseries": smap_timeseries,
        "smap_corridor_summary": smap_corridor_summary,
        "soil_moisture_grid": soil_moisture_grid,
        "gpm_raw_summary": gpm_raw_summary,
        "gpm_timeseries": gpm_timeseries,
        "gpm_corridor_summary": gpm_corridor_summary,
        "antecedent_rain_grid": antecedent_rain_grid,
    }
    missing_fields = _missing_fields(source_report)
    stale_risks = _stale_risks(source_report, stale_after_hours=stale_hours)
    warnings = _warnings(missing_fields=missing_fields, stale_risks=stale_risks)
    gee_summary = _gee_summary(artifacts)
    decision_output = _decision_output(
        summary=gee_summary,
        missing_fields=missing_fields,
        warnings=warnings,
    )
    field_answer = _field_answer(decision_output, gee_summary)
    results = _results(
        artifacts,
        include_grid=include_grid_rows,
        include_timeseries=include_timeseries_rows,
        limit=resolved_limit,
    )
    answerability = (
        "gee_environment_available"
        if gee_summary["available_artifact_count"] >= 3 and not missing_fields
        else "gee_environment_partial"
        if gee_summary["available_artifact_count"]
        else "gee_environment_missing"
    )

    return {
        "tool_id": GEE_ENVIRONMENT_TOOL_ID,
        "status": "completed",
        "project_id": project_id,
        "query": query,
        "assessment_kind": "read_only_gee_environment_workspace",
        "answerability": answerability,
        "source_status": _source_status(gee_summary["available_artifact_count"]),
        "decision": decision_output["decision"],
        "decision_output": decision_output,
        "field_answer": field_answer,
        "external_api_calls_made": False,
        "earth_engine_initialized": False,
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
        "filters": {
            "include_grid": include_grid_rows,
            "include_timeseries": include_timeseries_rows,
            "stale_after_hours": stale_hours,
        },
        "gee_environment": {
            "role": "GEE SMAP/GPM workspace hydrologic background evidence",
            "candidate_only": True,
            "runtime_safety_truth": False,
            "human_review_required": True,
            "summary": gee_summary,
            "decision_output": decision_output,
        },
        "gee_summary": gee_summary,
        "provenance_summary": _provenance_summary(source_report),
        "missing_fields": missing_fields,
        "warnings": warnings,
        "source_report": source_report,
        "result_count": len(results),
        "results": results,
        "standard_alignment": [
            "docs/specs/scout-weather-environment-sensing.md GEE SMAP/GPM family",
            "NASA/SMAP/SPL4SMGP/008 route-corridor SMAP L4 guidance",
            "NASA/GPM_L3/IMERG_V07 antecedent rain guidance",
            "SCOUT_OUTDOOR_AI_AGENT_STANDARD section 28.3 Data Confidence",
        ],
        "boundary": _closed_boundary(),
    }


def _load_artifact(
    root: Path,
    project: dict[str, Any],
    *,
    explicit_path: str | None,
    ref_keys: tuple[str, ...],
    fallbacks: tuple[str, ...],
    source_kind: str,
    source_report: list[dict[str, Any]],
) -> dict[str, Any]:
    refs = _candidate_paths(
        root,
        project,
        explicit_path=explicit_path,
        ref_keys=ref_keys,
        fallbacks=fallbacks,
    )
    for ref in refs:
        path = _resolve_project_path(root, ref)
        if not path.exists() or not path.is_file():
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            source_report.append(
                _source_report(
                    source_kind,
                    ref,
                    status="error",
                    error=str(exc),
                )
            )
            return {}
        if isinstance(payload, dict):
            source_report.append(
                _source_report(
                    source_kind,
                    ref,
                    status="loaded",
                    payload=payload,
                )
            )
            return payload
        if isinstance(payload, list):
            normalized = {"items": payload}
            source_report.append(
                _source_report(
                    source_kind,
                    ref,
                    status="loaded",
                    payload=normalized,
                )
            )
            return normalized
        source_report.append(
            _source_report(
                source_kind,
                ref,
                status="error",
                error="JSON artifact must be an object or list",
            )
        )
        return {}
    source_report.append(_source_report(source_kind, refs[0], status="missing"))
    return {}


def _candidate_paths(
    root: Path,
    project: dict[str, Any],
    *,
    explicit_path: str | None,
    ref_keys: tuple[str, ...],
    fallbacks: tuple[str, ...],
) -> list[str]:
    refs: list[str] = []
    if explicit_path:
        refs.append(explicit_path)
    for key in ref_keys:
        value = project.get(key)
        if isinstance(value, str) and value.strip():
            refs.append(value.strip())
    refs.extend(fallbacks)
    deduped: list[str] = []
    seen = set()
    for ref in refs:
        normalized = _project_ref(root, ref)
        if normalized and normalized not in seen:
            seen.add(normalized)
            deduped.append(normalized)
    return deduped


def _project_ref(root: Path, ref: str) -> str:
    path = Path(str(ref))
    if path.is_absolute():
        try:
            return str(path.relative_to(root))
        except ValueError:
            return str(path)
    return str(path)


def _resolve_project_path(root: Path, ref: str) -> Path:
    path = Path(str(ref))
    if path.is_absolute():
        return path
    return root / path


def _load_json_object(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _source_report(
    source_kind: str,
    source_path: str,
    *,
    status: str,
    payload: dict[str, Any] | None = None,
    error: str | None = None,
) -> dict[str, Any]:
    report: dict[str, Any] = {
        "source_kind": source_kind,
        "source_path": source_path,
        "status": status,
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
    }
    if error:
        report["error"] = error
    if payload:
        report.update(
            {
                "artifact_kind": payload.get("artifact_kind"),
                "schema_version": payload.get("schema_version"),
                "collection_ids": _collection_ids(payload),
                "dataset_ids": _collection_ids(payload),
                "source_refs": _source_refs(payload),
                "raw_response_hash": _raw_hash(payload),
                "stale_risk": _stale_risk(payload),
                "request_timestamp": _request_timestamp(payload),
                "normalized_artifact_ref": payload.get("normalized_artifact_ref"),
            }
        )
    return {key: value for key, value in report.items() if value not in (None, [], {})}


def _gee_summary(artifacts: dict[str, dict[str, Any]]) -> dict[str, Any]:
    return {
        "available_artifact_count": sum(1 for value in artifacts.values() if value),
        "smap_collection_id": "NASA/SMAP/SPL4SMGP/008",
        "gpm_collection_id": "NASA/GPM_L3/IMERG_V07",
        "supported_environment_datasets": [
            _compact_dataset(item) for item in GEE_ENVIRONMENT_DATASETS
        ],
        "smap_l4_corridor_summary": _compact_metric_summary(
            artifacts["smap_corridor_summary"],
            metric_keys=(
                "sm_surface",
                "sm_rootzone",
                "sm_profile",
                "sm_surface_wetness",
                "sm_rootzone_wetness",
                "surface_temp",
            ),
        ),
        "smap_timeseries_count": _event_count(artifacts["smap_timeseries"]),
        "soil_moisture_grid_feature_count": _feature_count(
            artifacts["soil_moisture_grid"]
        ),
        "gpm_imerg_corridor_summary": _compact_metric_summary(
            artifacts["gpm_corridor_summary"],
            metric_keys=(
                "rain_1h_mm",
                "rain_3h_mm",
                "rain_24h_mm",
                "rain_72h_mm",
                "max_hourly_mm",
                "p95_hourly_mm",
            ),
        ),
        "gpm_timeseries_count": _event_count(artifacts["gpm_timeseries"]),
        "antecedent_rain_grid_feature_count": _feature_count(
            artifacts["antecedent_rain_grid"]
        ),
        "gpm_raw_summary_available": bool(artifacts["gpm_raw_summary"]),
        "environment_factor_matrix_keys": sorted(artifacts["factor_matrix"].keys())[:12],
        "go_no_go_review_available": bool(artifacts["go_no_go_review"]),
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
    }


def _compact_dataset(item: dict[str, Any]) -> dict[str, Any]:
    return {
        "dataset_key": item.get("dataset_key"),
        "collection_id": item.get("collection_id"),
        "label": item.get("label"),
        "scout_use": item.get("scout_use"),
        "runtime_safety_truth": False,
    }


def _compact_metric_summary(
    payload: dict[str, Any],
    *,
    metric_keys: tuple[str, ...],
) -> dict[str, Any]:
    if not payload:
        return {}
    raw = payload.get("corridor_summary")
    if isinstance(raw, dict):
        payload = {**payload, **raw}
    metrics = payload.get("metrics")
    if isinstance(metrics, dict):
        payload = {**payload, **metrics}
    compact: dict[str, Any] = {}
    for key in metric_keys:
        value = payload.get(key)
        if isinstance(value, dict):
            compact[key] = {
                metric_key: value[metric_key]
                for metric_key in ("mean", "max", "p95", "latest", "trend")
                if metric_key in value
            }
        elif value is not None:
            compact[key] = value
    for key in ("latest_time", "trend_window", "raw_response_hash", "stale_risk"):
        if payload.get(key) is not None:
            compact[key] = payload[key]
    return compact


def _feature_count(payload: dict[str, Any]) -> int:
    features = payload.get("features")
    if isinstance(features, list):
        return len(features)
    items = payload.get("items")
    if isinstance(items, list):
        return len(items)
    return 1 if payload else 0


def _event_count(payload: dict[str, Any]) -> int:
    for key in ("events", "timeline", "items", "records", "timeseries"):
        value = payload.get(key)
        if isinstance(value, list):
            return len(value)
    return 1 if payload else 0


def _collection_ids(payload: dict[str, Any]) -> list[str]:
    values: list[Any] = []
    for key in ("collection_id", "dataset_id", "source_dataset_id"):
        if payload.get(key):
            values.append(payload[key])
    for key in ("collection_ids", "dataset_ids", "source_dataset_ids"):
        raw = payload.get(key)
        if isinstance(raw, list):
            values.extend(raw)
    source_report = payload.get("source_report")
    if isinstance(source_report, list):
        for item in source_report:
            if isinstance(item, dict):
                values.extend(_collection_ids(item))
    return _dedupe_text(str(value) for value in values if str(value).strip())


def _source_refs(payload: dict[str, Any]) -> list[str]:
    values: list[Any] = []
    for key in ("source_ref", "source_path", "normalized_artifact_ref"):
        if payload.get(key):
            values.append(payload[key])
    raw_refs = payload.get("source_refs")
    if isinstance(raw_refs, list):
        values.extend(raw_refs)
    return _dedupe_text(str(value) for value in values if str(value).strip())


def _raw_hash(payload: dict[str, Any]) -> str | None:
    for key in ("raw_response_hash", "raw_payload_hash", "sha256", "source_sha256"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _stale_risk(payload: dict[str, Any]) -> str | None:
    for key in ("stale_risk", "staleness_risk", "freshness_status"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _request_timestamp(payload: dict[str, Any]) -> str | None:
    for key in ("request_timestamp", "requested_at", "generated_at", "updated_at"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _missing_fields(source_report: list[dict[str, Any]]) -> list[str]:
    return [
        str(item["source_kind"])
        for item in source_report
        if item.get("status") in {"missing", "error"}
    ]


def _stale_risks(
    source_report: list[dict[str, Any]],
    *,
    stale_after_hours: float,
) -> list[str]:
    risks: list[str] = []
    now = datetime.now(timezone.utc)
    for item in source_report:
        if item.get("stale_risk") and str(item["stale_risk"]).lower() not in {
            "low",
            "fresh",
            "none",
        }:
            risks.append(f"{item['source_kind']} stale_risk={item['stale_risk']}")
        timestamp = item.get("request_timestamp")
        if not isinstance(timestamp, str):
            continue
        parsed = _parse_datetime(timestamp)
        if parsed is None:
            continue
        age_hours = (now - parsed).total_seconds() / 3600
        if age_hours > stale_after_hours:
            risks.append(
                f"{item['source_kind']} age_hours={age_hours:.1f}>{stale_after_hours:g}"
            )
    return _dedupe_text(risks)


def _parse_datetime(value: str) -> datetime | None:
    text = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def _warnings(
    *,
    missing_fields: list[str],
    stale_risks: list[str],
) -> list[str]:
    warnings: list[str] = []
    if missing_fields:
        warnings.append(
            "GEE SMAP/GPM environment evidence is incomplete; do not infer dry or stable conditions."
        )
    if "gee_smap_l4_corridor_summary" in missing_fields:
        warnings.append(
            "SMAP L4 corridor summary is missing; soil moisture review has an evidence gap."
        )
    if "gee_gpm_imerg_corridor_summary" in missing_fields:
        warnings.append(
            "GPM IMERG corridor summary is missing; antecedent rain review has an evidence gap."
        )
    warnings.extend(stale_risks)
    return _dedupe_text(warnings)


def _decision_output(
    *,
    summary: dict[str, Any],
    missing_fields: list[str],
    warnings: list[str],
) -> dict[str, Any]:
    smap = summary.get("smap_l4_corridor_summary")
    gpm = summary.get("gpm_imerg_corridor_summary")
    wetness = _metric_latest(smap, "sm_surface_wetness")
    rain_72h = _metric_latest(gpm, "rain_72h_mm")
    if missing_fields:
        decision = "DELAY"
        reason = "GEE hydrologic background evidence is incomplete."
        next_step = "重新產生或補齊 GEE SMAP/GPM artifacts 後再做 compound review。"
    elif (wetness is not None and wetness >= 0.7) or (
        rain_72h is not None and rain_72h >= 80
    ):
        decision = "CHANGE_PLAN"
        reason = "SMAP/GPM evidence indicates elevated wetness or antecedent rain review pressure."
        next_step = "與 CWA QPF、terrain/geology、route notes 合併形成人工複核候選。"
    else:
        decision = "REVIEW"
        reason = "GEE evidence is available as route-corridor hydrologic background."
        next_step = "不要用單點 SMAP 值判斷；用 corridor/bbox 與其他 evidence 合併檢查。"
    field_answer = (
        "GEE workspace evidence: "
        f"SMAP timeseries={summary['smap_timeseries_count']}, "
        f"soil_moisture_grid_features={summary['soil_moisture_grid_feature_count']}, "
        f"GPM timeseries={summary['gpm_timeseries_count']}, "
        f"antecedent_rain_grid_features={summary['antecedent_rain_grid_feature_count']}."
    )
    if wetness is not None:
        field_answer += f" SMAP surface wetness latest={wetness}."
    if rain_72h is not None:
        field_answer += f" GPM 72h rain latest={rain_72h}mm."
    return {
        "decisionObjectSchema": "ContextualPermission",
        "answerSourceToolId": GEE_ENVIRONMENT_TOOL_ID,
        "action": "review_gee_environment_evidence",
        "decision": decision,
        "allowed": False,
        "field_answer": field_answer,
        "main_reasons": [reason, *warnings[:2]],
        "next_action": next_step,
        "firstLayer": {
            "decision": "暫緩現場授權，作為行前候選證據檢查。",
            "limit": "GEE SMAP/GPM 只能作 route corridor/bbox hydrologic background，不可當 runtime safety truth。",
            "reason": reason,
            "nextStep": next_step,
        },
        "secondLayer": {
            "details": [field_answer],
            "uncertaintyNotes": [
                "SMAP 約 9km 格網，不可用單一點位值判斷坡面安全。",
                "GPM/IMERG 是衛星/模式降雨估計，需與 CWA、地形、地質與路況 notes 交叉檢查。",
                *warnings,
            ],
            "residualRisk": [
                "GEE-derived evidence requires human review before route decision use."
            ],
            "requiredConditions": [
                "candidate_only=true",
                "runtime_safety_truth=false",
                "human_review_required=true",
            ],
            "alternativeActions": [
                "Refresh GEE artifacts through explicit pretrip preparation.",
                "Compare with CWA QPF, recent observations, terrain, geology, and route notes.",
            ],
        },
        "runtimeSafetyTruth": False,
    }


def _metric_latest(summary: Any, key: str) -> float | None:
    if not isinstance(summary, dict):
        return None
    value = summary.get(key)
    if isinstance(value, dict):
        return _float_or_none(value.get("latest") or value.get("mean"))
    return _float_or_none(value)


def _field_answer(decision_output: dict[str, Any], summary: dict[str, Any]) -> str:
    text = str(decision_output.get("field_answer") or "").strip()
    text += (
        f" Collections: {summary['smap_collection_id']}, "
        f"{summary['gpm_collection_id']}."
    )
    return text


def _results(
    artifacts: dict[str, dict[str, Any]],
    *,
    include_grid: bool,
    include_timeseries: bool,
    limit: int,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if include_grid:
        rows.extend(
            _feature_rows(
                "soil_moisture_grid",
                artifacts["soil_moisture_grid"],
                limit=limit,
            )
        )
        rows.extend(
            _feature_rows(
                "antecedent_rain_grid",
                artifacts["antecedent_rain_grid"],
                limit=limit,
            )
        )
    if include_timeseries:
        rows.extend(
            _timeseries_rows(
                "smap_l4_timeseries",
                artifacts["smap_timeseries"],
                limit=limit,
            )
        )
        rows.extend(
            _timeseries_rows(
                "gpm_imerg_timeseries",
                artifacts["gpm_timeseries"],
                limit=limit,
            )
        )
    return rows[:limit]


def _feature_rows(kind: str, payload: dict[str, Any], *, limit: int) -> list[dict[str, Any]]:
    features = payload.get("features")
    if not isinstance(features, list):
        return []
    rows = []
    for feature in features[:limit]:
        if not isinstance(feature, dict):
            continue
        properties = feature.get("properties") if isinstance(feature.get("properties"), dict) else {}
        geometry = feature.get("geometry") if isinstance(feature.get("geometry"), dict) else {}
        rows.append(
            {
                "result_kind": kind,
                "label": properties.get("name") or properties.get("label") or kind,
                "properties": _compact_dict(properties, max_keys=8),
                "geometry_type": geometry.get("type"),
                "candidate_only": True,
                "runtime_safety_truth": False,
            }
        )
    return rows


def _timeseries_rows(kind: str, payload: dict[str, Any], *, limit: int) -> list[dict[str, Any]]:
    records: list[Any] = []
    for key in ("timeseries", "records", "events", "items", "timeline"):
        value = payload.get(key)
        if isinstance(value, list):
            records = value
            break
    rows = []
    for record in records[:limit]:
        if not isinstance(record, dict):
            continue
        rows.append(
            {
                "result_kind": kind,
                "time": record.get("time") or record.get("timestamp") or record.get("valid_time"),
                "properties": _compact_dict(record, max_keys=8),
                "candidate_only": True,
                "runtime_safety_truth": False,
            }
        )
    return rows


def _compact_dict(value: dict[str, Any], *, max_keys: int) -> dict[str, Any]:
    return {key: value[key] for key in list(value)[:max_keys]}


def _provenance_summary(source_report: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "loaded_sources": [
            item["source_kind"] for item in source_report if item.get("status") == "loaded"
        ],
        "missing_or_error_sources": [
            item["source_kind"]
            for item in source_report
            if item.get("status") in {"missing", "error"}
        ],
        "raw_response_hashes": [
            item["raw_response_hash"]
            for item in source_report
            if item.get("raw_response_hash")
        ],
        "collection_ids": sorted(
            {
                collection_id
                for item in source_report
                for collection_id in item.get("collection_ids", [])
                if str(collection_id).strip()
            }
        ),
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
    }


def _source_status(available_artifact_count: int) -> str:
    if available_artifact_count == 0:
        return "missing"
    if available_artifact_count < 4:
        return "partial"
    return "candidate_only"


def _bounded_limit(value: int) -> int:
    return max(1, min(MAX_RESULT_LIMIT, int(value or DEFAULT_RESULT_LIMIT)))


def _bool_value(value: bool | str | None, *, default: bool) -> bool:
    if value is None or value == "":
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() not in {"0", "false", "no", "off"}


def _float_or_default(value: float | int | str | None, *, default: float) -> float:
    parsed = _float_or_none(value)
    return default if parsed is None else parsed


def _float_or_none(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _dedupe_text(values: list[str] | Any) -> list[str]:
    seen = set()
    result = []
    for value in values:
        text = str(value).strip()
        if not text or text in seen:
            continue
        seen.add(text)
        result.append(text)
    return result


def _closed_boundary() -> dict[str, bool]:
    return {
        "read_only": True,
        "runtime_safety_truth": False,
        "live_safety_api_calls_allowed": False,
        "phase1_safety_mutation_allowed": False,
        "remote_outbound_send_allowed": False,
        "hardware_control_allowed": False,
        "raw_payloads_embedded": False,
        "model_output_is_runtime_truth": False,
    }
