from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from scout_gee_integration import GEE_ENVIRONMENT_DATASETS


GEE_ENVIRONMENT_TOOL_ID = "scout.ai.gee_environment.assess.v0"
GEE_ENVIRONMENT_OUTPUT_KIND = "scout_ai_gee_environment_tool_output"
GEE_ENVIRONMENT_REQUIRED_FIELDS = ("project_root",)
GEE_ENVIRONMENT_OPTIONAL_FIELDS = (
    "environment_package_path",
    "factor_matrix_path",
    "go_no_go_review_path",
    "smap_timeseries_path",
    "smap_corridor_summary_path",
    "soil_moisture_grid_path",
    "gpm_raw_summary_path",
    "gpm_timeseries_path",
    "gpm_corridor_summary_path",
    "antecedent_rain_grid_path",
    "risk_derivatives_path",
    "route_revalidation_report_path",
    "wetness_flash_flood_path",
    "include_grid",
    "include_timeseries",
    "stale_after_hours",
)

DEFAULT_STALE_AFTER_HOURS = 24.0
DEFAULT_RESULT_LIMIT = 6
MAX_RESULT_LIMIT = 12


def assess_scout_gee_environment(
    project_root: Path | str,
    *,
    query: str = "",
    environment_package_path: str | None = None,
    factor_matrix_path: str | None = None,
    go_no_go_review_path: str | None = None,
    smap_timeseries_path: str | None = None,
    smap_corridor_summary_path: str | None = None,
    soil_moisture_grid_path: str | None = None,
    gpm_raw_summary_path: str | None = None,
    gpm_timeseries_path: str | None = None,
    gpm_corridor_summary_path: str | None = None,
    antecedent_rain_grid_path: str | None = None,
    risk_derivatives_path: str | None = None,
    route_revalidation_report_path: str | None = None,
    wetness_flash_flood_path: str | None = None,
    include_grid: bool | str | None = None,
    include_timeseries: bool | str | None = None,
    stale_after_hours: float | int | str | None = None,
    limit: int = DEFAULT_RESULT_LIMIT,
) -> dict[str, Any]:
    """Read prepared GEE SMAP/GPM environment evidence from a Scout workspace.

    The tool does not initialize Earth Engine or access live GEE credentials.
    It only summarizes bounded artifacts generated by explicit pretrip map
    preparation.
    """

    root = Path(project_root)
    project = _load_json_object(root / "project.json")
    project_id = str(project.get("project_id") or project.get("id") or root.name)
    resolved_limit = _bounded_limit(limit)
    include_grid_rows = _bool_value(include_grid, default=True)
    include_timeseries_rows = _bool_value(include_timeseries, default=True)
    stale_hours = _float_or_default(
        stale_after_hours,
        default=DEFAULT_STALE_AFTER_HOURS,
    )

    source_report: list[dict[str, Any]] = []
    environment_package = _load_artifact(
        root,
        project,
        explicit_path=environment_package_path,
        ref_keys=("environment_evidence_package_ref",),
        fallbacks=("outputs/environment/environment_evidence_package.json",),
        source_kind="environment_evidence_package",
        source_report=source_report,
    )
    factor_matrix = _load_artifact(
        root,
        project,
        explicit_path=factor_matrix_path,
        ref_keys=("environment_factor_matrix_ref",),
        fallbacks=("outputs/environment/environment_factor_matrix.json",),
        source_kind="environment_factor_matrix",
        source_report=source_report,
    )
    go_no_go_review = _load_artifact(
        root,
        project,
        explicit_path=go_no_go_review_path,
        ref_keys=("go_no_go_review_draft_ref",),
        fallbacks=("outputs/environment/go_no_go_review_draft.json",),
        source_kind="go_no_go_review_draft",
        source_report=source_report,
    )
    smap_timeseries = _load_artifact(
        root,
        project,
        explicit_path=smap_timeseries_path,
        ref_keys=("gee_smap_l4_timeseries_ref",),
        fallbacks=("outputs/environment/gee/smap_l4_timeseries.json",),
        source_kind="gee_smap_l4_timeseries",
        source_report=source_report,
    )
    smap_corridor_summary = _load_artifact(
        root,
        project,
        explicit_path=smap_corridor_summary_path,
        ref_keys=("gee_smap_l4_corridor_summary_ref",),
        fallbacks=("outputs/environment/gee/smap_l4_corridor_summary.json",),
        source_kind="gee_smap_l4_corridor_summary",
        source_report=source_report,
    )
    soil_moisture_grid = _load_artifact(
        root,
        project,
        explicit_path=soil_moisture_grid_path,
        ref_keys=("gee_soil_moisture_grid_ref",),
        fallbacks=("outputs/environment/gee/soil_moisture_grid.geojson",),
        source_kind="gee_soil_moisture_grid",
        source_report=source_report,
    )
    gpm_raw_summary = _load_artifact(
        root,
        project,
        explicit_path=gpm_raw_summary_path,
        ref_keys=("gee_gpm_imerg_raw_summary_ref",),
        fallbacks=("outputs/environment/gee/gpm_imerg_raw_summary.json",),
        source_kind="gee_gpm_imerg_raw_summary",
        source_report=source_report,
    )
    gpm_timeseries = _load_artifact(
        root,
        project,
        explicit_path=gpm_timeseries_path,
        ref_keys=("gee_gpm_imerg_timeseries_ref",),
        fallbacks=("outputs/environment/gee/gpm_imerg_timeseries.json",),
        source_kind="gee_gpm_imerg_timeseries",
        source_report=source_report,
    )
    gpm_corridor_summary = _load_artifact(
        root,
        project,
        explicit_path=gpm_corridor_summary_path,
        ref_keys=("gee_gpm_imerg_corridor_summary_ref",),
        fallbacks=("outputs/environment/gee/gpm_imerg_corridor_summary.json",),
        source_kind="gee_gpm_imerg_corridor_summary",
        source_report=source_report,
    )
    antecedent_rain_grid = _load_artifact(
        root,
        project,
        explicit_path=antecedent_rain_grid_path,
        ref_keys=("gee_antecedent_rain_grid_ref",),
        fallbacks=("outputs/environment/gee/antecedent_rain_grid.geojson",),
        source_kind="gee_antecedent_rain_grid",
        source_report=source_report,
    )
    risk_derivatives = _load_artifact(
        root,
        project,
        explicit_path=risk_derivatives_path,
        ref_keys=("environment_risk_derivatives_ref",),
        fallbacks=("outputs/environment/derived/environment_risk_derivatives.json",),
        source_kind="environment_risk_derivatives",
        source_report=source_report,
        required=False,
    )
    route_revalidation_report = _load_artifact(
        root,
        project,
        explicit_path=route_revalidation_report_path,
        ref_keys=("route_revalidation_report_ref",),
        fallbacks=("outputs/environment/derived/route_revalidation_report.json",),
        source_kind="route_revalidation_report",
        source_report=source_report,
        required=False,
    )
    wetness_flash_flood = _load_artifact(
        root,
        project,
        explicit_path=wetness_flash_flood_path,
        ref_keys=("wetness_flash_flood_susceptibility_ref",),
        fallbacks=(
            "outputs/environment/derived/wetness_flash_flood_susceptibility.geojson",
        ),
        source_kind="wetness_flash_flood_susceptibility",
        source_report=source_report,
        required=False,
    )

    artifacts = {
        "environment_package": environment_package,
        "factor_matrix": factor_matrix,
        "go_no_go_review": go_no_go_review,
        "smap_timeseries": smap_timeseries,
        "smap_corridor_summary": smap_corridor_summary,
        "soil_moisture_grid": soil_moisture_grid,
        "gpm_raw_summary": gpm_raw_summary,
        "gpm_timeseries": gpm_timeseries,
        "gpm_corridor_summary": gpm_corridor_summary,
        "antecedent_rain_grid": antecedent_rain_grid,
        "risk_derivatives": risk_derivatives,
        "route_revalidation_report": route_revalidation_report,
        "wetness_flash_flood": wetness_flash_flood,
    }
    missing_fields = _missing_fields(source_report)
    stale_risks = _stale_risks(source_report, stale_after_hours=stale_hours)
    warnings = _warnings(missing_fields=missing_fields, stale_risks=stale_risks)
    gee_summary = _gee_summary(artifacts, root=root)
    decision_output = _decision_output(
        summary=gee_summary,
        missing_fields=missing_fields,
        warnings=warnings,
    )
    field_answer = _field_answer(decision_output, gee_summary, query=query)
    field_answer_source_refs = _field_answer_source_refs(query)
    field_answer_source_ref = field_answer_source_refs[0]
    results = _results(
        artifacts,
        include_grid=include_grid_rows,
        include_timeseries=include_timeseries_rows,
        limit=resolved_limit,
    )
    answerability = (
        "gee_environment_available"
        if gee_summary["available_artifact_count"] >= 3 and not missing_fields
        else "gee_environment_partial"
        if gee_summary["available_artifact_count"]
        else "gee_environment_missing"
    )

    return {
        "tool_id": GEE_ENVIRONMENT_TOOL_ID,
        "status": "completed",
        "project_id": project_id,
        "query": query,
        "assessment_kind": "read_only_gee_environment_workspace",
        "answerability": answerability,
        "source_status": _source_status(gee_summary["available_artifact_count"]),
        "decision": decision_output["decision"],
        "decision_output": decision_output,
        "field_answer": field_answer,
        "field_answer_priority": 100 if _gee_query_kind(query) else 10,
        "field_answer_source_ref": field_answer_source_ref,
        "field_answer_source_refs": field_answer_source_refs,
        "source_ref": field_answer_source_ref,
        "source_refs": field_answer_source_refs,
        "external_api_calls_made": False,
        "earth_engine_initialized": False,
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
        "filters": {
            "include_grid": include_grid_rows,
            "include_timeseries": include_timeseries_rows,
            "stale_after_hours": stale_hours,
        },
        "gee_environment": {
            "role": "GEE SMAP/GPM workspace hydrologic background evidence",
            "candidate_only": True,
            "runtime_safety_truth": False,
            "human_review_required": True,
            "summary": gee_summary,
            "decision_output": decision_output,
            "interpretation_limit": (
                "SMAP L4 is coarse route-corridor hydrologic background, "
                "not a single-slope passability or runtime safety conclusion."
            ),
        },
        "gee_summary": gee_summary,
        "provenance_summary": _provenance_summary(source_report),
        "missing_fields": missing_fields,
        "warnings": warnings,
        "source_report": source_report,
        "result_count": len(results),
        "results": results,
        "standard_alignment": [
            "docs/specs/scout-weather-environment-sensing.md GEE SMAP/GPM family",
            "NASA/SMAP/SPL4SMGP/008 route-corridor SMAP L4 guidance",
            "NASA/GPM_L3/IMERG_V07 antecedent rain guidance",
            "SCOUT_OUTDOOR_AI_AGENT_STANDARD section 28.3 Data Confidence",
        ],
        "boundary": _closed_boundary(),
    }


def _load_artifact(
    root: Path,
    project: dict[str, Any],
    *,
    explicit_path: str | None,
    ref_keys: tuple[str, ...],
    fallbacks: tuple[str, ...],
    source_kind: str,
    source_report: list[dict[str, Any]],
    required: bool = True,
) -> dict[str, Any]:
    refs = _candidate_paths(
        root,
        project,
        explicit_path=explicit_path,
        ref_keys=ref_keys,
        fallbacks=fallbacks,
    )
    for ref in refs:
        path = _resolve_project_path(root, ref)
        if not path.exists() or not path.is_file():
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            source_report.append(
                _source_report(
                    source_kind,
                    ref,
                    status="error",
                    error=str(exc),
                )
            )
            return {}
        if isinstance(payload, dict):
            source_report.append(
                _source_report(
                    source_kind,
                    ref,
                    status="loaded",
                    payload=payload,
                )
            )
            return payload
        if isinstance(payload, list):
            normalized = {"items": payload}
            source_report.append(
                _source_report(
                    source_kind,
                    ref,
                    status="loaded",
                    payload=normalized,
                )
            )
            return normalized
        source_report.append(
            _source_report(
                source_kind,
                ref,
                status="error",
                error="JSON artifact must be an object or list",
            )
        )
        return {}
    source_report.append(
        _source_report(
            source_kind,
            refs[0],
            status="missing" if required else "optional_missing",
        )
    )
    return {}


def _candidate_paths(
    root: Path,
    project: dict[str, Any],
    *,
    explicit_path: str | None,
    ref_keys: tuple[str, ...],
    fallbacks: tuple[str, ...],
) -> list[str]:
    refs: list[str] = []
    if explicit_path:
        refs.append(explicit_path)
    for key in ref_keys:
        value = project.get(key)
        if isinstance(value, str) and value.strip():
            refs.append(value.strip())
    refs.extend(fallbacks)
    deduped: list[str] = []
    seen = set()
    for ref in refs:
        normalized = _project_ref(root, ref)
        if normalized and normalized not in seen:
            seen.add(normalized)
            deduped.append(normalized)
    return deduped


def _project_ref(root: Path, ref: str) -> str:
    path = Path(str(ref))
    if path.is_absolute():
        try:
            return str(path.relative_to(root))
        except ValueError:
            return str(path)
    return str(path)


def _resolve_project_path(root: Path, ref: str) -> Path:
    path = Path(str(ref))
    if path.is_absolute():
        return path
    return root / path


def _load_json_object(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _source_report(
    source_kind: str,
    source_path: str,
    *,
    status: str,
    payload: dict[str, Any] | None = None,
    error: str | None = None,
) -> dict[str, Any]:
    report: dict[str, Any] = {
        "source_kind": source_kind,
        "source_path": source_path,
        "status": status,
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
        "smap_l4_interpretation_limit": (
            "coarse_route_corridor_background_not_single_slope_safety_truth"
        ),
    }
    if error:
        report["error"] = error
    if payload:
        report.update(
            {
                "artifact_kind": payload.get("artifact_kind"),
                "schema_version": payload.get("schema_version"),
                "collection_ids": _collection_ids(payload),
                "dataset_ids": _collection_ids(payload),
                "source_refs": _source_refs(payload),
                "raw_response_hash": _raw_hash(payload),
                "stale_risk": _stale_risk(payload),
                "request_timestamp": _request_timestamp(payload),
                "normalized_artifact_ref": payload.get("normalized_artifact_ref"),
            }
        )
    return {key: value for key, value in report.items() if value not in (None, [], {})}


def _gee_summary(
    artifacts: dict[str, dict[str, Any]],
    *,
    root: Path,
) -> dict[str, Any]:
    return {
        "available_artifact_count": sum(1 for value in artifacts.values() if value),
        "smap_collection_id": "NASA/SMAP/SPL4SMGP/008",
        "gpm_collection_id": "NASA/GPM_L3/IMERG_V07",
        "supported_environment_datasets": [
            _compact_dataset(item) for item in GEE_ENVIRONMENT_DATASETS
        ],
        "smap_l4_corridor_summary": _compact_metric_summary(
            artifacts["smap_corridor_summary"],
            metric_keys=(
                "sm_surface",
                "sm_rootzone",
                "sm_profile",
                "sm_surface_wetness",
                "sm_rootzone_wetness",
                "surface_temp",
            ),
        ),
        "smap_timeseries_count": _event_count(artifacts["smap_timeseries"]),
        "soil_moisture_grid_feature_count": _feature_count(
            artifacts["soil_moisture_grid"]
        ),
        "gpm_imerg_corridor_summary": _compact_metric_summary(
            artifacts["gpm_corridor_summary"],
            metric_keys=(
                "rain_1h_mm",
                "rain_3h_mm",
                "rain_24h_mm",
                "rain_72h_mm",
                "last_3h_mm",
                "last_24h_mm",
                "last_72h_mm",
                "max_hourly_mm",
                "p95_hourly_mm",
            ),
        ),
        "gpm_timeseries_count": _event_count(artifacts["gpm_timeseries"]),
        "antecedent_rain_grid_feature_count": _feature_count(
            artifacts["antecedent_rain_grid"]
        ),
        "gpm_raw_summary_available": bool(artifacts["gpm_raw_summary"]),
        "environment_factor_matrix_keys": sorted(artifacts["factor_matrix"].keys())[:12],
        "go_no_go_review_available": bool(artifacts["go_no_go_review"]),
        "antecedent_rain_grid_summary": _antecedent_rain_grid_summary(
            artifacts["antecedent_rain_grid"]
        ),
        "environment_factor_matrix_summary": _factor_matrix_summary(
            artifacts["factor_matrix"]
        ),
        "environment_risk_derivatives_summary": _risk_derivatives_summary(
            artifacts["risk_derivatives"]
        ),
        "wetness_compound_summary": _wetness_compound_summary(
            artifacts["wetness_flash_flood"]
        ),
        "route_revalidation_summary": _route_revalidation_summary(
            artifacts["route_revalidation_report"]
        ),
        "go_no_go_evidence_summary": _go_no_go_evidence_summary(
            artifacts["go_no_go_review"]
        ),
        "environment_package_provenance": _environment_package_provenance(
            artifacts["environment_package"],
            root=root,
        ),
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
    }


def _antecedent_rain_grid_summary(payload: dict[str, Any]) -> dict[str, Any]:
    features = payload.get("features")
    if not isinstance(features, list):
        return {}
    candidates: list[dict[str, Any]] = []
    for feature in features:
        if not isinstance(feature, dict):
            continue
        properties = feature.get("properties")
        geometry = feature.get("geometry")
        if not isinstance(properties, dict):
            properties = {}
        if not isinstance(geometry, dict):
            geometry = {}
        windows = {
            "3h": _first_float(properties, "rain_3h_mm", "last_3h_mm"),
            "24h": _first_float(properties, "rain_24h_mm", "last_24h_mm"),
            "72h": _first_float(properties, "rain_72h_mm", "last_72h_mm"),
        }
        available_values = [value for value in windows.values() if value is not None]
        if not available_values:
            continue
        coordinates = geometry.get("coordinates")
        lon = lat = None
        if (
            geometry.get("type") == "Point"
            and isinstance(coordinates, list)
            and len(coordinates) >= 2
        ):
            lon = _float_or_none(coordinates[0])
            lat = _float_or_none(coordinates[1])
        candidates.append(
            {
                "label": properties.get("name")
                or properties.get("label")
                or "antecedent rain grid cell",
                "lat": lat,
                "lon": lon,
                "rain_windows_mm": windows,
                "rank_value_mm": max(available_values),
                "timestamp": properties.get("timestamp")
                or properties.get("time")
                or payload.get("generated_at"),
            }
        )
    if not candidates:
        return {}
    return max(candidates, key=lambda item: item["rank_value_mm"])


def _factor_matrix_summary(payload: dict[str, Any]) -> dict[str, Any]:
    if not payload:
        return {}
    nested = payload.get("factors")
    factors = nested if isinstance(nested, dict) else payload
    ignored = {
        "artifact_kind",
        "schema_version",
        "project_id",
        "generated_at",
        "candidate_only",
        "runtime_safety_truth",
        "human_review_required",
        "boundary",
        "missing_evidence",
        "cwa_time_metadata",
        "generated_at_hour",
        "route_name",
        "time_precision",
        "timezone",
    }
    available: list[str] = []
    partial_missing: list[str] = []
    for key, value in factors.items():
        if key in ignored:
            continue
        if _has_substantive_value(value):
            available.append(str(key))
        partial_missing.extend(_none_paths(value, prefix=str(key)))
    explicit_missing = _string_items(payload.get("missing_evidence"))
    return {
        "available": sorted(available),
        "partial_missing": sorted(_dedupe_text(partial_missing)),
        "missing_evidence": explicit_missing,
    }


def _risk_derivatives_summary(payload: dict[str, Any]) -> dict[str, Any]:
    if not payload:
        return {}
    counts = payload.get("counts")
    if not isinstance(counts, dict):
        counts = {}
    candidate_counts = {
        str(key).removesuffix("_count"): value
        for key, value in counts.items()
        if str(key).endswith("_candidate_count")
    }
    return {
        "candidate_counts": candidate_counts,
        "headline": payload.get("headline"),
        "output_refs": payload.get("output_refs")
        if isinstance(payload.get("output_refs"), dict)
        else {},
    }


def _wetness_compound_summary(payload: dict[str, Any]) -> dict[str, Any]:
    features = payload.get("features")
    if not isinstance(features, list):
        return {}
    rows: list[dict[str, Any]] = []
    complete_count = 0
    dimensions_seen = {"qpf": False, "smap": False, "recent_rain": False, "terrain": False}
    for feature in features:
        if not isinstance(feature, dict):
            continue
        properties = feature.get("properties")
        if not isinstance(properties, dict):
            properties = {}
        supporting = properties.get("supporting_metrics")
        if not isinstance(supporting, dict):
            supporting = {}
        merged = {**properties, **supporting}
        present = {
            "qpf": _mapping_has_value(merged, ("qpf",)),
            "smap": _mapping_has_value(merged, ("smap", "soil_moisture")),
            "recent_rain": _mapping_has_value(
                merged,
                ("gpm_recent_rainfall", "recent_rainfall", "rain_72h"),
            ),
            "terrain": _mapping_has_value(merged, ("slope", "terrain", "elevation")),
        }
        for key, value in present.items():
            dimensions_seen[key] = dimensions_seen[key] or value
        if all(present.values()):
            complete_count += 1
        rows.append(
            {
                "label": properties.get("label")
                or properties.get("name")
                or properties.get("source_segment_id")
                or "unnamed segment",
                "severity": str(properties.get("severity") or "unknown"),
                "score": _float_or_none(properties.get("score")) or 0.0,
            }
        )
    high_rows = [row for row in rows if row["severity"].casefold() == "high"]
    ranked = sorted(high_rows or rows, key=lambda row: row["score"], reverse=True)
    missing_dimensions = [key for key, present in dimensions_seen.items() if not present]
    return {
        "candidate_count": len(rows),
        "high_count": len(high_rows),
        "complete_four_factor_count": complete_count,
        "top_labels": [str(row["label"]) for row in ranked[:5]],
        "missing_dimensions": missing_dimensions,
    }


def _route_revalidation_summary(payload: dict[str, Any]) -> dict[str, Any]:
    if not payload:
        return {}
    stale = _string_items(
        payload.get("stale_evidence")
        or payload.get("stale_refs")
        or payload.get("stale_sources")
    )
    missing = _string_items(
        payload.get("missing_evidence")
        or payload.get("missing_refs")
        or payload.get("missing_sources")
    )
    return {
        "status": payload.get("status"),
        "event_date": payload.get("event_date"),
        "stale_evidence": stale,
        "missing_evidence": missing,
        "notes": _string_items(payload.get("notes")),
    }


def _go_no_go_evidence_summary(payload: dict[str, Any]) -> dict[str, Any]:
    refs = _string_items(payload.get("evidence_source_refs"))
    cwa_refs = [ref for ref in refs if "/cwa/" in ref.casefold()]
    gee_refs = [ref for ref in refs if "/gee/" in ref.casefold()]
    terrain_tokens = ("/terrain/", "terrain", "geology", "risk_score", "dtm")
    terrain_refs = [
        ref
        for ref in refs
        if any(token in ref.casefold() for token in terrain_tokens)
    ]
    return {
        "cwa_refs": cwa_refs,
        "gee_refs": gee_refs,
        "terrain_refs": terrain_refs,
        "other_refs": [
            ref
            for ref in refs
            if ref not in cwa_refs and ref not in gee_refs and ref not in terrain_refs
        ],
        "missing_evidence": _string_items(payload.get("missing_evidence")),
    }


def _environment_package_provenance(
    payload: dict[str, Any],
    *,
    root: Path,
) -> dict[str, Any]:
    refs = _string_items(payload.get("source_refs"))
    existing: list[str] = []
    missing: list[str] = []
    for ref in refs:
        (existing if _resolve_project_path(root, ref).is_file() else missing).append(ref)
    return {
        "listed_count": len(refs),
        "existing_count": len(existing),
        "missing_count": len(missing),
        "missing_refs": missing,
        "declared_missing_evidence": _string_items(payload.get("missing_evidence")),
        "complete": bool(refs) and not missing,
    }


def _first_float(payload: dict[str, Any], *keys: str) -> float | None:
    for key in keys:
        value = _float_or_none(payload.get(key))
        if value is not None:
            return value
    return None


def _has_substantive_value(value: Any) -> bool:
    if isinstance(value, dict):
        return any(_has_substantive_value(item) for item in value.values())
    if isinstance(value, list):
        return any(_has_substantive_value(item) for item in value)
    return value is not None and value != ""


def _none_paths(value: Any, *, prefix: str) -> list[str]:
    if value is None:
        return [prefix]
    if not isinstance(value, dict):
        return []
    paths: list[str] = []
    for key, child in value.items():
        paths.extend(_none_paths(child, prefix=f"{prefix}.{key}"))
    return paths


def _mapping_has_value(payload: dict[str, Any], tokens: tuple[str, ...]) -> bool:
    for key, value in payload.items():
        normalized_key = str(key).casefold()
        if any(token in normalized_key for token in tokens) and value not in (None, "", []):
            return True
    return False


def _string_items(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    rows: list[str] = []
    for item in value:
        if isinstance(item, str) and item.strip():
            rows.append(item.strip())
        elif isinstance(item, dict):
            label = item.get("source_ref") or item.get("ref") or item.get("field")
            if label:
                rows.append(str(label))
    return _dedupe_text(rows)


def _compact_dataset(item: dict[str, Any]) -> dict[str, Any]:
    return {
        "dataset_key": item.get("dataset_key"),
        "collection_id": item.get("collection_id"),
        "label": item.get("label"),
        "scout_use": item.get("scout_use"),
        "bands": item.get("bands"),
        "temporal_resolution": item.get("temporal_resolution"),
        "spatial_resolution_m": item.get("spatial_resolution_m"),
        "candidate_only": True,
        "human_review_required": item.get("human_review_required", True),
        "runtime_safety_truth": False,
    }


def _compact_metric_summary(
    payload: dict[str, Any],
    *,
    metric_keys: tuple[str, ...],
) -> dict[str, Any]:
    if not payload:
        return {}
    raw = payload.get("corridor_summary")
    if isinstance(raw, dict):
        payload = {**payload, **raw}
    values = payload.get("values")
    if isinstance(values, dict):
        payload = {**payload, **values}
    metrics = payload.get("metrics")
    if isinstance(metrics, dict):
        payload = {**payload, **metrics}
    compact: dict[str, Any] = {}
    for key in metric_keys:
        value = payload.get(key)
        if isinstance(value, dict):
            compact[key] = {
                metric_key: value[metric_key]
                for metric_key in ("mean", "max", "p95", "latest", "trend")
                if metric_key in value
            }
        elif value is not None:
            compact[key] = value
    for key in ("latest_time", "trend_window", "raw_response_hash", "stale_risk"):
        if payload.get(key) is not None:
            compact[key] = payload[key]
    return compact


def _feature_count(payload: dict[str, Any]) -> int:
    features = payload.get("features")
    if isinstance(features, list):
        return len(features)
    items = payload.get("items")
    if isinstance(items, list):
        return len(items)
    return 1 if payload else 0


def _event_count(payload: dict[str, Any]) -> int:
    for key in ("events", "timeline", "items", "records", "timeseries"):
        value = payload.get(key)
        if isinstance(value, list):
            return len(value)
    return 1 if payload else 0


def _collection_ids(payload: dict[str, Any]) -> list[str]:
    values: list[Any] = []
    for key in ("collection_id", "dataset_id", "source_dataset_id"):
        if payload.get(key):
            values.append(payload[key])
    for key in ("collection_ids", "dataset_ids", "source_dataset_ids"):
        raw = payload.get(key)
        if isinstance(raw, list):
            values.extend(raw)
    source_report = payload.get("source_report")
    if isinstance(source_report, list):
        for item in source_report:
            if isinstance(item, dict):
                values.extend(_collection_ids(item))
    return _dedupe_text(str(value) for value in values if str(value).strip())


def _source_refs(payload: dict[str, Any]) -> list[str]:
    values: list[Any] = []
    for key in ("source_ref", "source_path", "normalized_artifact_ref"):
        if payload.get(key):
            values.append(payload[key])
    raw_refs = payload.get("source_refs")
    if isinstance(raw_refs, list):
        values.extend(raw_refs)
    return _dedupe_text(str(value) for value in values if str(value).strip())


def _raw_hash(payload: dict[str, Any]) -> str | None:
    for key in ("raw_response_hash", "raw_payload_hash", "sha256", "source_sha256"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _stale_risk(payload: dict[str, Any]) -> str | None:
    for key in ("stale_risk", "staleness_risk", "freshness_status"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _request_timestamp(payload: dict[str, Any]) -> str | None:
    for key in ("request_timestamp", "requested_at", "generated_at", "updated_at"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


def _missing_fields(source_report: list[dict[str, Any]]) -> list[str]:
    return [
        str(item["source_kind"])
        for item in source_report
        if item.get("status") in {"missing", "error"}
    ]


def _stale_risks(
    source_report: list[dict[str, Any]],
    *,
    stale_after_hours: float,
) -> list[str]:
    risks: list[str] = []
    now = datetime.now(timezone.utc)
    for item in source_report:
        if item.get("stale_risk") and str(item["stale_risk"]).lower() not in {
            "low",
            "fresh",
            "none",
        }:
            risks.append(f"{item['source_kind']} stale_risk={item['stale_risk']}")
        timestamp = item.get("request_timestamp")
        if not isinstance(timestamp, str):
            continue
        parsed = _parse_datetime(timestamp)
        if parsed is None:
            continue
        age_hours = (now - parsed).total_seconds() / 3600
        if age_hours > stale_after_hours:
            risks.append(
                f"{item['source_kind']} age_hours={age_hours:.1f}>{stale_after_hours:g}"
            )
    return _dedupe_text(risks)


def _parse_datetime(value: str) -> datetime | None:
    text = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def _warnings(
    *,
    missing_fields: list[str],
    stale_risks: list[str],
) -> list[str]:
    warnings: list[str] = []
    if missing_fields:
        warnings.append(
            "GEE SMAP/GPM environment evidence is incomplete; do not infer dry or stable conditions."
        )
    if "gee_smap_l4_corridor_summary" in missing_fields:
        warnings.append(
            "SMAP L4 corridor summary is missing; soil moisture review has an evidence gap."
        )
    if "gee_gpm_imerg_corridor_summary" in missing_fields:
        warnings.append(
            "GPM IMERG corridor summary is missing; antecedent rain review has an evidence gap."
        )
    warnings.extend(stale_risks)
    return _dedupe_text(warnings)


def _decision_output(
    *,
    summary: dict[str, Any],
    missing_fields: list[str],
    warnings: list[str],
) -> dict[str, Any]:
    smap = summary.get("smap_l4_corridor_summary")
    gpm = summary.get("gpm_imerg_corridor_summary")
    wetness = _metric_latest(smap, "sm_surface_wetness")
    rain_72h = _metric_latest(gpm, "rain_72h_mm")
    if missing_fields:
        decision = "DELAY"
        reason = "GEE hydrologic background evidence is incomplete."
        next_step = "重新產生或補齊 GEE SMAP/GPM artifacts 後再做 compound review。"
    elif (wetness is not None and wetness >= 0.7) or (
        rain_72h is not None and rain_72h >= 80
    ):
        decision = "CHANGE_PLAN"
        reason = "SMAP/GPM evidence indicates elevated wetness or antecedent rain review pressure."
        next_step = "與 CWA QPF、terrain/geology、route notes 合併形成人工複核候選。"
    else:
        decision = "REVIEW"
        reason = "GEE evidence is available as route-corridor hydrologic background."
        next_step = "不要用單點 SMAP 值判斷；用 corridor/bbox 與其他 evidence 合併檢查。"
    field_answer = (
        "GEE workspace evidence: "
        f"SMAP timeseries={summary['smap_timeseries_count']}, "
        f"soil_moisture_grid_features={summary['soil_moisture_grid_feature_count']}, "
        f"GPM timeseries={summary['gpm_timeseries_count']}, "
        f"antecedent_rain_grid_features={summary['antecedent_rain_grid_feature_count']}."
    )
    if wetness is not None:
        field_answer += f" SMAP surface wetness latest={wetness}."
    if rain_72h is not None:
        field_answer += f" GPM 72h rain latest={rain_72h}mm."
    return {
        "decisionObjectSchema": "ContextualPermission",
        "answerSourceToolId": GEE_ENVIRONMENT_TOOL_ID,
        "action": "review_gee_environment_evidence",
        "decision": decision,
        "allowed": False,
        "field_answer": field_answer,
        "main_reasons": [reason, *warnings[:2]],
        "next_action": next_step,
        "firstLayer": {
            "decision": "暫緩現場授權，作為行前候選證據檢查。",
            "limit": "GEE SMAP/GPM 只能作 route corridor/bbox hydrologic background，不可當 runtime safety truth。",
            "reason": reason,
            "nextStep": next_step,
        },
        "secondLayer": {
            "details": [field_answer],
            "uncertaintyNotes": [
                "SMAP L4 約 11km/3h 格網，只能作粗解析度 route corridor/bbox 水文背景。",
                "不可用單一 SMAP 點位值判斷坡面落石、崩塌或通行安全。",
                "GPM/IMERG 是衛星/模式降雨估計，需與 CWA、地形、地質與路況 notes 交叉檢查。",
                *warnings,
            ],
            "residualRisk": [
                "GEE-derived evidence requires human review before route decision use."
            ],
            "requiredConditions": [
                "candidate_only=true",
                "runtime_safety_truth=false",
                "human_review_required=true",
            ],
            "alternativeActions": [
                "Refresh GEE artifacts through explicit pretrip preparation.",
                "Compare with CWA QPF, recent observations, terrain, geology, and route notes.",
            ],
        },
        "runtimeSafetyTruth": False,
    }


def _metric_latest(summary: Any, key: str) -> float | None:
    if not isinstance(summary, dict):
        return None
    value = summary.get(key)
    if isinstance(value, dict):
        return _float_or_none(value.get("latest") or value.get("mean"))
    return _float_or_none(value)


def _field_answer(
    decision_output: dict[str, Any],
    summary: dict[str, Any],
    *,
    query: str,
) -> str:
    query_kind = _gee_query_kind(query)
    smap = summary.get("smap_l4_corridor_summary")
    gpm = summary.get("gpm_imerg_corridor_summary")
    if query_kind == "smap_soil_moisture" and isinstance(smap, dict):
        return (
            "SMAP L4 corridor soil moisture："
            f"surface={_display_metric(_metric_stat(smap, 'sm_surface', 'latest'))}，"
            f"rootzone={_display_metric(_metric_stat(smap, 'sm_rootzone', 'latest'))}，"
            f"profile={_display_metric(_metric_stat(smap, 'sm_profile', 'latest'))}。"
        )
    if query_kind == "smap_surface_wetness" and isinstance(smap, dict):
        return (
            "SMAP surface wetness："
            f"latest={_display_metric(_metric_stat(smap, 'sm_surface_wetness', 'latest'))}，"
            f"mean={_display_metric(_metric_stat(smap, 'sm_surface_wetness', 'mean'))}，"
            f"max={_display_metric(_metric_stat(smap, 'sm_surface_wetness', 'max'))}，"
            f"p95={_display_metric(_metric_stat(smap, 'sm_surface_wetness', 'p95'))}，"
            f"trend={_display_metric(_metric_stat(smap, 'sm_surface_wetness', 'trend'))}。"
        )
    if query_kind == "antecedent_rain_location":
        item = summary.get("antecedent_rain_grid_summary")
        if isinstance(item, dict) and item:
            windows = item.get("rain_windows_mm")
            if not isinstance(windows, dict):
                windows = {}
            values = "，".join(
                f"{window}={value} mm"
                for window, value in windows.items()
                if value is not None
            ) or "累積量=unavailable"
            return (
                "antecedent rain grid 最高累積雨量位於 "
                f"{item.get('label') or 'unnamed grid cell'}（"
                f"lat={_display_metric(item.get('lat'))}, "
                f"lon={_display_metric(item.get('lon'))}），{values}。"
            )
        return "antecedent rain grid 沒有可排序的累積雨量 feature。"
    if query_kind == "gpm_latest" and isinstance(gpm, dict):
        values = {
            "1h": _metric_stat(gpm, "rain_1h_mm", "latest"),
            "3h": _first_metric_stat(gpm, ("rain_3h_mm", "last_3h_mm"), "latest"),
            "24h": _first_metric_stat(
                gpm, ("rain_24h_mm", "last_24h_mm"), "latest"
            ),
            "72h": _first_metric_stat(
                gpm, ("rain_72h_mm", "last_72h_mm"), "latest"
            ),
        }
        trends = [
            _metric_stat(gpm, key, "trend")
            for key in (
                "rain_72h_mm",
                "last_72h_mm",
                "rain_24h_mm",
                "last_24h_mm",
                "rain_3h_mm",
                "last_3h_mm",
                "rain_1h_mm",
            )
        ]
        trend = next((value for value in trends if value is not None), None)
        value_text = "，".join(
            f"{window}={_display_metric(value)} mm" for window, value in values.items()
        )
        return f"GPM IMERG corridor：latest {value_text}；trend={_display_metric(trend)}。"
    if query_kind == "factor_matrix":
        matrix = summary.get("environment_factor_matrix_summary")
        if isinstance(matrix, dict) and matrix:
            available = ", ".join(matrix.get("available") or []) or "none"
            partial = ", ".join(matrix.get("partial_missing") or []) or "none"
            explicit = ", ".join(matrix.get("missing_evidence") or []) or "none"
            return (
                f"environment factor matrix 已有資料：{available}；"
                f"部分缺欄：{partial}；missing evidence：{explicit}。"
            )
    if query_kind == "risk_derivatives":
        derivatives = summary.get("environment_risk_derivatives_summary")
        if isinstance(derivatives, dict) and derivatives:
            counts = derivatives.get("candidate_counts")
            if not isinstance(counts, dict):
                counts = {}
            text = ", ".join(f"{key}={value}" for key, value in counts.items())
            return f"environment risk derivatives compound candidate counts：{text or 'none'}。"
    if query_kind == "four_factor_compound":
        compound = summary.get("wetness_compound_summary")
        if isinstance(compound, dict) and compound:
            labels = "、".join(compound.get("top_labels") or []) or "none"
            missing = set(compound.get("missing_dimensions") or [])
            missing_text = []
            if "qpf" in missing:
                missing_text.append("per-segment QPF")
            if "smap" in missing:
                missing_text.append("per-segment SMAP")
            if "recent_rain" in missing:
                missing_text.append("GPM recent-rain")
            if "terrain" in missing:
                missing_text.append("terrain")
            return (
                f"完整四因子複合候選 {compound.get('complete_four_factor_count', 0)} 段；"
                f"濕滑/溪溝暴漲候選 {compound.get('candidate_count', 0)} 段，"
                f"其中高風險 {compound.get('high_count', 0)} 段；"
                f"高分位置：{labels}；缺少 {', '.join(missing_text) or 'none'} join，"
                "不能視為完整四因子複合候選。"
            )
    if query_kind == "route_revalidation":
        report = summary.get("route_revalidation_summary")
        if isinstance(report, dict) and report:
            stale = ", ".join(report.get("stale_evidence") or []) or "none"
            missing = ", ".join(report.get("missing_evidence") or []) or "none"
            event_date = report.get("event_date") or "missing"
            notes = " ".join(report.get("notes") or []) or "none"
            return (
                f"route revalidation status={report.get('status') or 'unknown'}；"
                f"event_date={event_date}；named stale evidence={stale}；"
                f"named missing evidence={missing}；notes={notes}。"
            )
    if query_kind == "go_no_go_refs":
        refs = summary.get("go_no_go_evidence_summary")
        if isinstance(refs, dict) and refs:
            cwa = refs.get("cwa_refs") or []
            gee = refs.get("gee_refs") or []
            terrain = refs.get("terrain_refs") or []
            cwa_labels = [_source_ref_label(ref) for ref in cwa]
            gee_labels = [_source_ref_label(ref) for ref in gee]
            terrain_labels = [_source_ref_label(ref) for ref in terrain]
            return (
                f"go/no-go draft：CWA weather refs={len(cwa)} "
                f"（{', '.join(cwa_labels) or 'none'}）；GEE weather refs={len(gee)} "
                f"（{', '.join(gee_labels) or 'none'}）；terrain refs={len(terrain)} "
                f"（{', '.join(terrain_labels) or 'none'}）。"
            )
    if query_kind == "package_provenance":
        provenance = summary.get("environment_package_provenance")
        if isinstance(provenance, dict) and provenance:
            missing = ", ".join(provenance.get("missing_refs") or []) or "none"
            return (
                "environment evidence package provenance："
                f"listed={provenance.get('listed_count', 0)}，"
                f"existing={provenance.get('existing_count', 0)}，"
                f"missing={provenance.get('missing_count', 0)}；"
                f"missing refs={missing}。"
            )

    text = str(decision_output.get("field_answer") or "").strip()
    text += (
        f" Collections: {summary['smap_collection_id']}, "
        f"{summary['gpm_collection_id']}."
    )
    text += (
        " SMAP L4 is coarse 11km/3h candidate-only hydrologic background for "
        "route corridor/bbox review, not a single-slope passability or runtime "
        "safety conclusion."
    )
    return text


def _metric_stat(summary: dict[str, Any], key: str, stat: str) -> Any:
    value = summary.get(key)
    if isinstance(value, dict):
        if stat in value:
            return value[stat]
        if stat == "latest":
            return value.get("mean")
        return None
    return value if stat == "latest" else None


def _first_metric_stat(
    summary: dict[str, Any],
    keys: tuple[str, ...],
    stat: str,
) -> Any:
    for key in keys:
        value = _metric_stat(summary, key, stat)
        if value is not None:
            return value
    return None


def _display_metric(value: Any) -> str:
    return "unavailable" if value is None else str(value)


def _source_ref_label(source_ref: str) -> str:
    return Path(source_ref).stem


def _gee_query_kind(query: str) -> str | None:
    normalized = query.casefold()
    if "surface wetness" in normalized and "smap" in normalized:
        return "smap_surface_wetness"
    if "smap" in normalized and all(
        token in normalized for token in ("surface", "rootzone", "profile")
    ):
        return "smap_soil_moisture"
    if "antecedent rain" in normalized and any(
        token in normalized for token in ("最高", "位置", "highest", "location")
    ):
        return "antecedent_rain_location"
    if "gpm" in normalized and any(
        token in normalized for token in ("最新", "趨勢", "latest", "trend")
    ):
        return "gpm_latest"
    if "environment factor matrix" in normalized:
        return "factor_matrix"
    if "environment risk derivatives" in normalized:
        return "risk_derivatives"
    if all(token in normalized for token in ("qpf", "smap", "terrain")) and any(
        token in normalized for token in ("recent rain", "複合候選", "compound")
    ):
        return "four_factor_compound"
    if "route revalidation" in normalized:
        return "route_revalidation"
    if "go/no-go" in normalized and any(
        token in normalized for token in ("evidence", "引用", "refs")
    ):
        return "go_no_go_refs"
    if "environment evidence package" in normalized and "provenance" in normalized:
        return "package_provenance"
    return None


def _field_answer_source_refs(query: str) -> list[str]:
    query_kind = _gee_query_kind(query)
    by_kind = {
        "smap_soil_moisture": [
            "outputs/environment/gee/smap_l4_corridor_summary.json"
        ],
        "smap_surface_wetness": [
            "outputs/environment/gee/smap_l4_corridor_summary.json"
        ],
        "antecedent_rain_location": [
            "outputs/environment/gee/antecedent_rain_grid.geojson"
        ],
        "gpm_latest": [
            "outputs/environment/gee/gpm_imerg_corridor_summary.json"
        ],
        "factor_matrix": ["outputs/environment/environment_factor_matrix.json"],
        "risk_derivatives": [
            "outputs/environment/derived/environment_risk_derivatives.json"
        ],
        "four_factor_compound": [
            "outputs/environment/derived/wetness_flash_flood_susceptibility.geojson",
            "outputs/environment/environment_factor_matrix.json",
        ],
        "route_revalidation": [
            "outputs/environment/derived/route_revalidation_report.json"
        ],
        "go_no_go_refs": ["outputs/environment/go_no_go_review_draft.json"],
        "package_provenance": [
            "outputs/environment/environment_evidence_package.json"
        ],
    }
    return by_kind.get(
        query_kind,
        ["outputs/environment/environment_evidence_package.json"],
    )


def _results(
    artifacts: dict[str, dict[str, Any]],
    *,
    include_grid: bool,
    include_timeseries: bool,
    limit: int,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if include_grid:
        rows.extend(
            _feature_rows(
                "soil_moisture_grid",
                artifacts["soil_moisture_grid"],
                limit=limit,
            )
        )
        rows.extend(
            _feature_rows(
                "antecedent_rain_grid",
                artifacts["antecedent_rain_grid"],
                limit=limit,
            )
        )
    if include_timeseries:
        rows.extend(
            _timeseries_rows(
                "smap_l4_timeseries",
                artifacts["smap_timeseries"],
                limit=limit,
            )
        )
        rows.extend(
            _timeseries_rows(
                "gpm_imerg_timeseries",
                artifacts["gpm_timeseries"],
                limit=limit,
            )
        )
    return rows[:limit]


def _feature_rows(kind: str, payload: dict[str, Any], *, limit: int) -> list[dict[str, Any]]:
    features = payload.get("features")
    if not isinstance(features, list):
        return []
    rows = []
    for feature in features[:limit]:
        if not isinstance(feature, dict):
            continue
        properties = feature.get("properties") if isinstance(feature.get("properties"), dict) else {}
        geometry = feature.get("geometry") if isinstance(feature.get("geometry"), dict) else {}
        rows.append(
            {
                "result_kind": kind,
                "label": properties.get("name") or properties.get("label") or kind,
                "properties": _compact_dict(properties, max_keys=8),
                "geometry_type": geometry.get("type"),
                "candidate_only": True,
                "runtime_safety_truth": False,
            }
        )
    return rows


def _timeseries_rows(kind: str, payload: dict[str, Any], *, limit: int) -> list[dict[str, Any]]:
    records: list[Any] = []
    for key in ("timeseries", "records", "events", "items", "timeline"):
        value = payload.get(key)
        if isinstance(value, list):
            records = value
            break
    rows = []
    for record in records[:limit]:
        if not isinstance(record, dict):
            continue
        rows.append(
            {
                "result_kind": kind,
                "time": record.get("time") or record.get("timestamp") or record.get("valid_time"),
                "properties": _compact_dict(record, max_keys=8),
                "candidate_only": True,
                "runtime_safety_truth": False,
            }
        )
    return rows


def _compact_dict(value: dict[str, Any], *, max_keys: int) -> dict[str, Any]:
    return {key: value[key] for key in list(value)[:max_keys]}


def _provenance_summary(source_report: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "loaded_sources": [
            item["source_kind"] for item in source_report if item.get("status") == "loaded"
        ],
        "missing_or_error_sources": [
            item["source_kind"]
            for item in source_report
            if item.get("status") in {"missing", "error"}
        ],
        "raw_response_hashes": [
            item["raw_response_hash"]
            for item in source_report
            if item.get("raw_response_hash")
        ],
        "collection_ids": sorted(
            {
                collection_id
                for item in source_report
                for collection_id in item.get("collection_ids", [])
                if str(collection_id).strip()
            }
        ),
        "candidate_only": True,
        "runtime_safety_truth": False,
        "human_review_required": True,
    }


def _source_status(available_artifact_count: int) -> str:
    if available_artifact_count == 0:
        return "missing"
    if available_artifact_count < 4:
        return "partial"
    return "candidate_only"


def _bounded_limit(value: int) -> int:
    return max(1, min(MAX_RESULT_LIMIT, int(value or DEFAULT_RESULT_LIMIT)))


def _bool_value(value: bool | str | None, *, default: bool) -> bool:
    if value is None or value == "":
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() not in {"0", "false", "no", "off"}


def _float_or_default(value: float | int | str | None, *, default: float) -> float:
    parsed = _float_or_none(value)
    return default if parsed is None else parsed


def _float_or_none(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _dedupe_text(values: list[str] | Any) -> list[str]:
    seen = set()
    result = []
    for value in values:
        text = str(value).strip()
        if not text or text in seen:
            continue
        seen.add(text)
        result.append(text)
    return result


def _closed_boundary() -> dict[str, bool]:
    return {
        "read_only": True,
        "runtime_safety_truth": False,
        "live_safety_api_calls_allowed": False,
        "phase1_safety_mutation_allowed": False,
        "remote_outbound_send_allowed": False,
        "hardware_control_allowed": False,
        "raw_payloads_embedded": False,
        "model_output_is_runtime_truth": False,
    }
