from __future__ import annotations

from tests.qualification.phase3_contracts import (
    AuthorityBoundarySpec,
    CommandResourceSpec,
    DashboardDomainSpec,
    DependencyEdgeSpec,
    DomainRiskProfile,
)


PHASE3_DESIGN_CANONICAL_SHA256 = (
    "5a3b14b3ea9fd64a086bb106b277140c0bb0ecc5ef3d6ed8415e347f43736112"
)
PHASE2_JOINT_CLOSURE_REPORT_CANONICAL_SHA256 = (
    "a7056c72a3ba9633e55e19e695801a03bbfb88335ba5b9a8b6ef993c1f41cc95"
)
PHASE2_REPORT_CANONICAL_SHA256 = (
    "0ed412162d4253d1b8e0d16b920430c789014d3d0535117130349b1bda10e98d"
)
PHASE2_DETERMINISM_ADDENDUM_CANONICAL_SHA256 = (
    "52da07186d4fbe4a21413bf5bac31217be0bace1a401fe869f645aaf424090b3"
)
PHASE2_DETERMINISM_ADDENDUM_REV1_CANONICAL_SHA256 = (
    "94f6e5605b58b27128071a291ace179e02adcfd46711011bd5f5ee1f28976239"
)
PHASE2_MANIFEST_SEMANTIC_SHA256 = (
    "9fd09a176cdad141a3d62f2d124ea07c5421e9f18bd3b77d94acb0c30096ccc1"
)
PHASE2_REPORT_SEMANTIC_SHA256 = (
    "2905a18fd3d733752e9c26ecb7a412d66a47152f0a8fa7a3199f9bd943fb9a27"
)

CANONICAL_ROUTE_DISPOSITION: tuple[tuple[str, str], ...] = (
    ("home", "dashboard-shell-control"),
    ("features-workspace", "workspace-lifecycle"),
    ("features-import-new-trip", "workspace-lifecycle"),
    ("features-country-material-pool", "workspace-lifecycle"),
    ("map", "geospatial-weather-navigation"),
    ("timeline", "dashboard-shell-control"),
    ("features-lbs", "geospatial-weather-navigation"),
    ("outdoor-route-context", "route-intelligence"),
    ("outdoor-pace-fit", "route-intelligence"),
    ("outdoor-pace-fit-body-index", "body-index-privacy"),
    ("outdoor-permission", "contextual-permission"),
    ("outdoor-architecture", "route-intelligence"),
    ("outdoor-weather", "geospatial-weather-navigation"),
    ("outdoor-navigation", "geospatial-weather-navigation"),
    ("emergency", "safety-emergency"),
    ("agent", "assistant-planner"),
    ("living", "safety-emergency"),
    ("surface-debug", "dashboard-shell-control"),
    ("debug", "dashboard-shell-control"),
    ("observer", "observer-hardware-boundary"),
    ("settings", "dashboard-shell-control"),
    ("diagnostic", "separate-runtime-diagnostic"),
)

FIXTURE_CLASSES = (
    "current",
    "known_historical",
    "malformed",
    "unknown_version",
    "stale_upstream",
    "interrupted_write",
)


def _risk(
    domain_id: str,
    tier: int,
    refs: tuple[str, ...],
    **axes: bool,
) -> DomainRiskProfile:
    return DomainRiskProfile(
        domain_id=domain_id,
        declared_tier=tier,  # type: ignore[arg-type]
        source_refs=refs,
        **axes,
    )


DOMAIN_SPECS: tuple[DashboardDomainSpec, ...] = (
    DashboardDomainSpec(
        "contextual-permission",
        _risk(
            "contextual-permission",
            0,
            (
                "scout_contextual_permission_workbench.py",
                "scout_contextual_permission_workbench_api.py",
            ),
            shared_authority_writer=True,
            human_confirmation=True,
            downstream_decision_impact=True,
        ),
        ("outdoor-permission",),
        ("/admin/pretrip/projects/{project_id}/mission-baseline",),
        (
            "scout_contextual_permission_workbench.py",
            "scout_contextual_permission_workbench_api.py",
        ),
        ("mission-baseline", "permission-projection", "review-session"),
        FIXTURE_CLASSES,
        ("baseline_capability", "projection", "review_binding", "rebuild_admission"),
        ("no-baseline", "legacy-sparse", "projection-stale", "write-in-doubt"),
        ("propose", "accept-review", "rebuild", "recover"),
        ("ready", "external-action-required", "quarantined"),
        ("migrate-legacy", "rebuild-stale-projection", "recover-interrupted-write"),
        ("admission", "confirmation", "authority"),
    ),
    DashboardDomainSpec(
        "safety-emergency",
        _risk(
            "safety-emergency",
            0,
            (
                "scout_runtime_safety_gate_models.py",
                "scout_runtime_safety_reducer.py",
                "scout_runtime_safety_state_store.py",
                "scout_emergency_mobile_closed_loop_sandbox.py",
            ),
            runtime_safety_authority=True,
            shared_authority_writer=True,
            durable_publication=True,
            human_confirmation=True,
        ),
        ("emergency", "living"),
        ("/admin/dashboard/living", "/admin/dashboard/emergency"),
        (
            "scout_runtime_safety_gate_models.py",
            "scout_runtime_safety_reducer.py",
            "scout_runtime_safety_state_store.py",
            "scout_emergency_mobile_closed_loop_sandbox.py",
            "scout_emergency_mobile_closed_loop_api.py",
        ),
        ("runtime-gate-event", "reducer-decision", "approval-request", "sandbox-run"),
        FIXTURE_CLASSES,
        ("event_identity", "policy_version", "candidate_level", "approval_binding"),
        ("candidate", "pending-approval", "stale-receipt", "write-in-doubt"),
        ("reduce", "request-approval", "confirm", "recover"),
        ("candidate-only", "pending-approval", "fail-closed"),
        ("rerun-reducer", "renew-bound-approval", "recover-state-store"),
        ("safety", "admission", "confirmation", "authority"),
    ),
    DashboardDomainSpec(
        "workspace-lifecycle",
        _risk(
            "workspace-lifecycle",
            0,
            (
                "dashboard_workspace_publication.py",
                "dashboard_connected_preparation.py",
                "pretrip_import.py",
            ),
            shared_authority_writer=True,
            durable_publication=True,
            background_execution=True,
            downstream_decision_impact=True,
        ),
        ("features-workspace", "features-import-new-trip", "features-country-material-pool"),
        ("/admin/dashboard/workspaces", "/admin/pretrip/projects"),
        (
            "dashboard_workspace_publication.py",
            "dashboard_workspace_operations.py",
            "dashboard_connected_preparation.py",
            "pretrip_workspace_project.py",
            "pretrip_import.py",
            "pretrip_layer_preparation.py",
        ),
        ("workspace-generation", "preparation-journal", "project-manifest", "material-pool"),
        FIXTURE_CLASSES,
        ("project_identity", "generation_identity", "journal_state", "publication_pointer"),
        ("unprepared", "staged", "published", "cleanup-pending", "write-in-doubt"),
        ("stage", "prepare", "publish", "switch", "recover"),
        ("published", "recoverable", "quarantined"),
        ("recover-journal", "retry-preparation", "discard-staged"),
        ("admission", "authority"),
    ),
    DashboardDomainSpec(
        "geospatial-weather-navigation",
        _risk(
            "geospatial-weather-navigation",
            1,
            (
                "admin_weather_overlay.py",
                "navigation_terrain_projection.py",
                "pretrip_layer_preparation.py",
            ),
            durable_publication=True,
            external_effects=True,
            downstream_decision_impact=True,
        ),
        ("map", "features-lbs", "outdoor-weather", "outdoor-navigation"),
        ("/admin/pretrip/projects/{project_id}/weather", "/admin/pretrip/projects/{project_id}/layer-preparation", "/admin/tiles"),
        (
            "admin_weather_overlay.py",
            "weather_imagery_freshness.py",
            "weather_imagery_tile_cache.py",
            "navigation_terrain_projection.py",
            "navigation_terrain_projection_store.py",
            "pretrip_layer_preparation.py",
            "admin_imagery_sources.py",
            "admin_local_raster_tiles.py",
        ),
        ("weather-overlay", "imagery-cache", "navigation-projection", "layer-manifest"),
        FIXTURE_CLASSES,
        ("route_hash", "source_hash", "freshness", "projection_status"),
        ("missing", "fresh", "stale", "malformed", "interrupted"),
        ("build", "refresh", "invalidate", "recover"),
        ("ready", "stale", "quarantined"),
        ("refresh-projection", "rebuild-cache", "recover-publication"),
    ),
    DashboardDomainSpec(
        "route-intelligence",
        _risk(
            "route-intelligence",
            1,
            (
                "scout_route_context_tool.py",
                "scout_route_architecture_tool.py",
                "pretrip_pace_fit_collection.py",
            ),
            durable_publication=True,
            downstream_decision_impact=True,
        ),
        ("outdoor-route-context", "outdoor-pace-fit", "outdoor-architecture"),
        ("/admin/pretrip/projects/{project_id}/briefings/route-context",),
        (
            "scout_route_context_tool.py",
            "scout_route_architecture_tool.py",
            "pretrip_route_context_collection.py",
            "pretrip_route_architecture_collection.py",
            "pretrip_pace_fit_collection.py",
        ),
        ("route-context-pack", "route-architecture", "pace-fit", "planned-eta"),
        FIXTURE_CLASSES,
        ("route_identity", "source_manifest", "planned_eta_parent", "candidate_boundary"),
        ("missing", "candidate", "stale", "unknown-version", "interrupted"),
        ("assess", "collect", "refresh", "recover"),
        ("candidate-ready", "stale", "quarantined"),
        ("recollect", "rebind-route", "recover-publication"),
    ),
    DashboardDomainSpec(
        "assistant-planner",
        _risk(
            "assistant-planner",
            1,
            ("assistant_api.py", "assistant_readiness_check.py", "assistant_skill_router.py"),
            external_effects=True,
            downstream_decision_impact=True,
        ),
        ("agent",),
        ("/assistant",),
        ("assistant_api.py", "assistant_readiness_check.py", "assistant_skill_router.py", "assistant_context.py"),
        ("assistant-status", "tool-plan", "candidate-answer"),
        FIXTURE_CLASSES,
        ("workspace_identity", "tool_manifest", "plan_status", "candidate_boundary"),
        ("not-ready", "ready", "candidate", "tool-failed"),
        ("readiness", "plan", "execute-readonly", "replan"),
        ("candidate-ready", "typed-failure", "quarantined"),
        ("refresh-readiness", "replan"),
    ),
    DashboardDomainSpec(
        "body-index-privacy",
        _risk(
            "body-index-privacy",
            1,
            ("admin_api.py", "pretrip_pace_fit_collection.py"),
            privacy_sensitive=True,
            durable_publication=True,
            background_execution=True,
            downstream_decision_impact=True,
        ),
        ("outdoor-pace-fit-body-index",),
        ("/admin/dashboard/body-index",),
        ("admin_api.py", "pretrip_pace_fit_collection.py"),
        ("sanitized-body-index", "body-index-watch-status", "pace-advisory"),
        FIXTURE_CLASSES,
        ("source_hash", "sanitization_version", "watch_generation", "advisory_boundary"),
        ("unavailable", "sanitized", "watching", "stale", "interrupted"),
        ("import", "merge", "watch-start", "watch-stop", "recover"),
        ("sanitized-ready", "unavailable", "quarantined"),
        ("reimport", "restart-watch", "recover-publication"),
        ("privacy", "confirmation"),
    ),
    DashboardDomainSpec(
        "observer-hardware-boundary",
        _risk(
            "observer-hardware-boundary",
            1,
            ("scout_sensorlogger_mqtt_observer.py", "ingress_observer_supervisor.py"),
            privacy_sensitive=True,
            durable_publication=True,
            external_effects=True,
            background_execution=True,
            downstream_decision_impact=True,
        ),
        ("observer",),
        ("/admin/dashboard/living",),
        (
            "scout_sensorlogger_mqtt_observer.py",
            "ingress_observer_supervisor.py",
            "runtime_input_admission.py",
            "scout_gnss_hardware_observer.py",
            "scout_lorawan_client_observer.py",
        ),
        ("normalized-observer-record", "observer-status", "safety-admission-candidate"),
        FIXTURE_CLASSES,
        ("payload_hash", "normalization_version", "admission_status", "hardware_boundary"),
        ("unrecognized", "normalized", "rejected", "stale", "interrupted"),
        ("normalize", "admit", "start", "stop", "recover"),
        ("normalized-candidate", "rejected", "quarantined"),
        ("retry-normalization", "renew-admission", "recover-store"),
        ("privacy", "admission", "authority"),
    ),
    DashboardDomainSpec(
        "dashboard-shell-control",
        _risk(
            "dashboard-shell-control",
            2,
            ("docs/admin/scout-dashboard-v0.1.html", "admin_api.py"),
        ),
        ("home", "timeline", "surface-debug", "debug", "settings"),
        ("/admin/dashboard",),
        ("docs/admin/scout-dashboard-v0.1.html", "admin_api.py"),
        ("local-settings", "route-selection", "readiness-view"),
        ("current", "malformed", "unknown_version"),
        ("route", "settings_schema", "startup_write_count", "diagnostic_separation"),
        ("loading", "ready", "invalid-settings"),
        ("navigate", "validate-settings", "reload"),
        ("ready", "validation-error"),
        ("reload-settings",),
    ),
)


DEPENDENCY_EDGES: tuple[DependencyEdgeSpec, ...] = (
    DependencyEdgeSpec(
        "workspace-to-route",
        "workspace-generation",
        "route-identity",
        "workspace-lifecycle",
        "route-intelligence",
        "reviewed",
        ("project_id", "generation_id", "route_sha256"),
        "consumer parent generation and route hash match publication",
        "workspace generation or route hash changes",
        "rebind-route",
        "candidate-only",
        ("dashboard_workspace_publication.py:publish", "scout_route_context_tool.py:project.json"),
    ),
    DependencyEdgeSpec(
        "route-to-geospatial",
        "route-identity",
        "weather-imagery-navigation",
        "route-intelligence",
        "geospatial-weather-navigation",
        "candidate",
        ("project_id", "route_sha256"),
        "all projections bind the same route hash",
        "route hash changes",
        "refresh-projection",
        "advisory-only",
        ("pretrip_layer_preparation.py:route_summary_ref", "navigation_terrain_projection.py:route"),
    ),
    DependencyEdgeSpec(
        "route-to-context-timing",
        "route-identity",
        "route-context-and-reference-timing",
        "workspace-lifecycle",
        "route-intelligence",
        "reviewed",
        ("route_sha256", "timing_sha256"),
        "context and timing share route parent",
        "route or timing identity changes",
        "recollect",
        "candidate-only",
        ("scout_route_context_tool.py:route", "pretrip_pace_fit_collection.py:route"),
    ),
    DependencyEdgeSpec(
        "context-to-baseline",
        "route-context-and-reference-timing",
        "reviewed-mission-baseline",
        "route-intelligence",
        "contextual-permission",
        "reviewed",
        ("route_sha256", "context_sha256", "timing_sha256"),
        "baseline review binds every upstream identity",
        "context timing or route identity changes",
        "migrate-legacy",
        "admission-input",
        ("scout_contextual_permission_workbench.py:baseline", "scout_route_context_tool.py:source_report"),
    ),
    DependencyEdgeSpec(
        "baseline-to-permission",
        "reviewed-mission-baseline",
        "permission-rules-and-projection",
        "contextual-permission",
        "contextual-permission",
        "approved",
        ("baseline_id", "baseline_sha256", "review_id"),
        "projection binds accepted baseline review",
        "baseline subject or policy changes",
        "rebuild-stale-projection",
        "admission-input",
        ("scout_contextual_permission_workbench.py:projection",),
    ),
    DependencyEdgeSpec(
        "permission-to-safety",
        "permission-rules-and-projection",
        "planned-eta-and-safety-review-packet",
        "contextual-permission",
        "safety-emergency",
        "approved",
        ("projection_sha256", "policy_version", "generation"),
        "safety packet binds current reviewed permission projection",
        "projection policy or generation changes",
        "renew-bound-approval",
        "deterministic-admission-only",
        ("scout_emergency_mobile_closed_loop_sandbox.py:approval", "scout_runtime_safety_reducer.py:policy"),
    ),
    DependencyEdgeSpec(
        "body-to-pace",
        "sanitized-body-index",
        "pace-advisory",
        "body-index-privacy",
        "route-intelligence",
        "sanitized",
        ("body_index_sha256", "sanitization_version"),
        "pace advisory binds sanitized derivative only",
        "body index or sanitizer changes",
        "recollect",
        "advisory-only",
        ("admin_api.py:scout_pace_coefficient", "docs/admin/scout-dashboard-v0.1.html:bodyIndexMetrics"),
    ),
    DependencyEdgeSpec(
        "observer-to-safety",
        "normalized-observer-record",
        "deterministic-safety-admission",
        "observer-hardware-boundary",
        "safety-emergency",
        "normalized",
        ("observation_sha256", "normalization_version", "policy_version"),
        "observer evidence enters only deterministic admission",
        "observation normalization or policy changes",
        "renew-admission",
        "deterministic-admission-only",
        ("scout_sensorlogger_mqtt_observer.py:sensor_vitals", "runtime_input_admission.py:admit_runtime_observation_input"),
    ),
    DependencyEdgeSpec(
        "assistant-runtime-forbidden",
        "assistant-candidate-output",
        "runtime-safety-truth",
        "assistant-planner",
        "safety-emergency",
        "candidate",
        ("candidate_sha256", "tool_plan_sha256"),
        "no direct edge is authorized",
        "any assistant output changes",
        "deterministic-admission",
        "forbidden-direct",
        ("assistant_api.py:candidate", "scout_runtime_safety_gate_models.py:boundary"),
        False,
    ),
)


AUTHORITY_BOUNDARIES: tuple[AuthorityBoundarySpec, ...] = (
    AuthorityBoundarySpec("assistant-candidate-runtime", "candidate", "runtime_safety_truth", False, False, ("assistant_api.py",)),
    AuthorityBoundarySpec("body-raw-runtime", "raw", "runtime_safety_truth", False, False, ("admin_api.py",)),
    AuthorityBoundarySpec("body-sanitized-pace", "sanitized", "runtime_state", True, False, ("pretrip_pace_fit_collection.py",)),
    AuthorityBoundarySpec("observer-normalized-admission", "normalized", "runtime_safety_truth", True, True, ("scout_runtime_safety_gate_adapters.py",)),
    AuthorityBoundarySpec("reviewed-permission-admission", "approved", "runtime_safety_truth", True, True, ("scout_contextual_permission_workbench.py",)),
    AuthorityBoundarySpec("sandbox-outbound", "approved", "outbound", False, True, ("scout_emergency_mobile_closed_loop_sandbox.py",)),
    AuthorityBoundarySpec("sandbox-hardware", "approved", "hardware", False, True, ("scout_emergency_mobile_closed_loop_sandbox.py",)),
)


COMMAND_RESOURCES: tuple[CommandResourceSpec, ...] = (
    CommandResourceSpec(
        "workspace-stage",
        "workspace-lifecycle",
        "dashboard_workspace_publication.py:stage",
        read_set=("workspace:{project}",),
        write_set=("staged:{project}",),
        lock_set=("preparation-lock:{project}",),
        identity_set=("generation:{project}",),
        source_callsites=("dashboard_workspace_publication.py:194",),
        replay_observations=("production-stage",),
    ),
    CommandResourceSpec(
        "workspace-publish",
        "workspace-lifecycle",
        "dashboard_workspace_publication.py:publish",
        read_set=("staged:{project}",),
        write_set=("workspace:{project}",),
        lock_set=("preparation-lock:{project}", "generation-lock:{project}"),
        journal_set=("publication-journal:{project}",),
        pointer_set=("live-pointer:{project}",),
        identity_set=("generation:{project}",),
        source_callsites=("dashboard_workspace_publication.py:297",),
        replay_observations=("production-publish",),
    ),
    CommandResourceSpec(
        "workspace-recover",
        "workspace-lifecycle",
        "dashboard_workspace_publication.py:recover_pending",
        read_set=("publication-journal:{project}",),
        write_set=("workspace:{project}",),
        lock_set=("preparation-lock:{project}", "generation-lock:{project}"),
        journal_set=("publication-journal:{project}",),
        pointer_set=("live-pointer:{project}",),
        identity_set=("generation:{project}",),
        source_callsites=("dashboard_workspace_publication.py:463",),
        replay_observations=("production-startup-recovery",),
    ),
    CommandResourceSpec(
        "body-index-import",
        "body-index-privacy",
        "admin_api.py:_import_dashboard_body_index",
        read_set=("body-source:{project}",),
        write_set=("body-index:{project}",),
        lock_set=("body-index-lock:{project}",),
        identity_set=("body-index-generation:{project}",),
        source_callsites=("admin_api.py:1097",),
        replay_observations=("production-sanitized-import",),
    ),
    CommandResourceSpec(
        "body-watch-start",
        "body-index-privacy",
        "admin_api.py:_start_dashboard_body_index_watcher",
        read_set=("body-source:{project}",),
        write_set=("body-watch:{project}",),
        lock_set=("body-index-lock:{project}",),
        identity_set=("body-index-generation:{project}",),
        source_callsites=("admin_api.py:1383",),
        replay_observations=("production-watch-start",),
    ),
    CommandResourceSpec(
        "body-watch-stop",
        "body-index-privacy",
        "admin_api.py:_stop_dashboard_body_index_watcher",
        read_set=("body-watch:{project}",),
        write_set=("body-watch:{project}",),
        lock_set=("body-index-lock:{project}",),
        identity_set=("body-index-generation:{project}",),
        source_callsites=("admin_api.py:1407",),
        replay_observations=("production-watch-stop",),
    ),
    CommandResourceSpec(
        "permission-rebuild",
        "contextual-permission",
        "scout_contextual_permission_workbench.py:rebuild",
        read_set=("mission-baseline:{project}", "permission-policy:{project}"),
        write_set=("permission-projection:{project}",),
        lock_set=("permission-store:{project}",),
        receipt_set=("permission-admission:{project}",),
        identity_set=("baseline-generation:{project}", "policy-generation:{project}"),
        source_callsites=("scout_contextual_permission_workbench.py",),
        replay_observations=("phase2-rebuild",),
    ),
    CommandResourceSpec(
        "safety-confirm",
        "safety-emergency",
        "scout_emergency_mobile_closed_loop_sandbox.py:approval",
        read_set=("permission-projection:{project}", "safety-candidate:{project}"),
        write_set=("safety-review:{project}",),
        receipt_set=("safety-approval:{project}",),
        identity_set=("policy-generation:{project}",),
        source_callsites=("scout_emergency_mobile_closed_loop_sandbox.py",),
        replay_observations=("production-sandbox-approval",),
    ),
    CommandResourceSpec(
        "geospatial-refresh",
        "geospatial-weather-navigation",
        "pretrip_layer_preparation.py:run_layer_preparation",
        read_set=("workspace:{project}", "generation:{project}"),
        write_set=("geospatial-projection:{project}",),
        lock_set=("preparation-lock:{project}",),
        pointer_set=("live-pointer:{project}",),
        identity_set=("generation:{project}",),
        source_callsites=("pretrip_layer_preparation.py:431",),
        replay_observations=("fixture-backed-overlay",),
    ),
    CommandResourceSpec(
        "route-read",
        "route-intelligence",
        "scout_route_context_tool.py:assess_scout_route_context",
        read_set=("workspace:{project}", "generation:{project}", "route:{project}"),
        identity_set=("generation:{project}",),
        source_callsites=("scout_route_context_tool.py:34",),
        replay_observations=("fixture-backed-route-assess",),
    ),
)


DOMAIN_IDS = tuple(item.domain_id for item in DOMAIN_SPECS)
RUNTIME_DIAGNOSTIC_ROUTE = "diagnostic"


__all__ = [
    "AUTHORITY_BOUNDARIES",
    "CANONICAL_ROUTE_DISPOSITION",
    "COMMAND_RESOURCES",
    "DEPENDENCY_EDGES",
    "DOMAIN_IDS",
    "DOMAIN_SPECS",
    "FIXTURE_CLASSES",
    "PHASE2_REPORT_CANONICAL_SHA256",
    "PHASE2_JOINT_CLOSURE_REPORT_CANONICAL_SHA256",
    "PHASE2_DETERMINISM_ADDENDUM_CANONICAL_SHA256",
    "PHASE2_DETERMINISM_ADDENDUM_REV1_CANONICAL_SHA256",
    "PHASE2_MANIFEST_SEMANTIC_SHA256",
    "PHASE2_REPORT_SEMANTIC_SHA256",
    "PHASE3_DESIGN_CANONICAL_SHA256",
    "RUNTIME_DIAGNOSTIC_ROUTE",
]
